apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-caching-availability
  labels:
    tenant: rhtap
spec:
  groups:
    - name: caching_availability
      interval: 1m
      rules:
        - record: konflux_up
          expr: |
            min by (namespace, service) (
              squid_up{namespace="caching", service="squid"}
            )
        - record: konflux_up
          expr: |
            min by (namespace, service) (
              nginx_up{namespace="caching", service="artifact-registry-proxy"}
            )
    - name: artifact_registry_proxy_performance
      interval: 1m
      rules:
        # Record rule: calculate total request rate
        - record: artifact_registry_proxy:http_requests:rate5m
          expr: sum by (source_cluster, namespace, service) (rate(http_requests_total{namespace="caching", service="artifact-registry-proxy"}[5m]))

        # Record rule: calculate error rate (5xx responses)
        - record: artifact_registry_proxy:http_errors:rate5m
          expr: sum by (source_cluster, namespace, service) (rate(http_requests_total{namespace="caching", service="artifact-registry-proxy", status=~"5.."}[5m]))
