apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-api-server-availability-alerting-rules
  labels:
    tenant: rhtap

spec:
  groups:
  - name: api_server_service_konflux_up_alert
    interval: 1m
    rules:
    - alert: KonfluxAPIServerHighErrorRate
      expr: |
        (
          sum by(source_cluster) (
            code:apiserver_request_total:rate5m{code=~"5.."}
          ) /
          sum by(source_cluster) (
            code:apiserver_request_total:rate5m{code!="0"}
          )
        ) * 100 > 10
      for: 15m
      labels:
        severity: critical
        slo: "true"
        component: api-server
      annotations:
        summary: >-
          API Server 5XX error count in cluster {{ $labels.source_cluster }}
        description: "API Server is experiencing 10% of 5XX failures based on the total requests for 15min in cluster {{ $labels.source_cluster }}"
        alert_team_handle: <!subteam^S05Q1P4Q2TG>
        team: konflux-infra
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/infra/sre/api_server_error_rate_alert.md

#  - name: api_cpu_usage
#    interval: 1m
#    rules:
#      - alert: KonfluxAPIServerHighCPUUsage
#        expr: |
#          sum by (source_cluster) (rate(process_cpu_seconds_total{job="apiserver"}[5m])) > 0.8 * count by (source_cluster) (node_cpu_seconds_total{mode="idle"})
#        for: 5m
#        labels:
#          severity: critical
#          slo: "true"
#          component: api-server
#        annotations:
#          summary: API Server CPU usage is above 80% in {{ $labels.source_cluster }}
#          description: >-
#            API Server process CPU consumption is above 80% for 5 minutes in cluster {{ $labels.source_cluster }}.
#          alert_team_handle: <!subteam^S05Q1P4Q2TG>
#          team: konflux-infra
#          runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/infra/sre/apiserver_HighCPUUsage.md

  - name: api_server_latency
    interval: 1m
    rules:
    - alert: KonfluxAPIServerLatencyWarning
      expr: |
        (
          sum by (source_cluster) (rate(apiserver_request_duration_seconds_bucket{le="1.0", verb!~"WATCH|LIST"}[5m]))
          /
          sum by (source_cluster) (rate(apiserver_request_duration_seconds_count{verb!~"WATCH|LIST"}[5m]))
        ) < 0.99
      for: 15m
      labels:
        severity: warning
        component: api-server
        team: konflux-infra
      annotations:
        summary: "API Server high latency detected in cluster {{ $labels.source_cluster }}"
        description: "More than 1% of requests exceeded 1s for 15m. Impact: Slow CLI/UI response. Action: Check for Control Plane load or resource pressure."
        alert_routing_key: infra
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/infra/sre/apiserver_HighP99Latency.md

    - alert: KonfluxAPIServerLatencySLOCritical
      expr: |
        (
          sum by (source_cluster) (rate(apiserver_request_duration_seconds_bucket{le="1.0", verb!~"WATCH|LIST"}[1h]))
          /
          sum by (source_cluster) (rate(apiserver_request_duration_seconds_count{verb!~"WATCH|LIST"}[1h]))
          < 0.95
        )
        and
        (
          sum by (source_cluster) (rate(apiserver_request_duration_seconds_bucket{le="1.0", verb!~"WATCH|LIST"}[5m]))
          /
          sum by (source_cluster) (rate(apiserver_request_duration_seconds_count{verb!~"WATCH|LIST"}[5m]))
          < 0.95
        )
      for: 5m
      labels:
        severity: critical
        slo: "true"
        component: api-server
        team: konflux-infra
      annotations:
        summary: "API Server Latency: Critical SLO Breach ({{ $labels.source_cluster }})"
        description: "More than 5% of API requests exceeded 1s latency over the last 1h and 5m. Impact: High risk of system-wide timeouts. Action: Immediate check of Etcd health and admission webhooks."
        alert_team_handle: <!subteam^S05Q1P4Q2TG>
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/infra/sre/apiserver_HighP99Latency.md

  - name: api_memory_usage
    interval: 1m
    rules:
      - alert: KonfluxAPIServerHighMemoryUsage
        expr: |
          (
            sum(process_resident_memory_bytes{job="apiserver"}) by (source_cluster)
          /
            sum(node_memory_MemTotal_bytes) by (source_cluster)
          ) * 100 > 80
        for: 5m
        labels:
          severity: critical
          slo: "true"
          component: api-server
        annotations:
          summary: API Server memory usage is above 80% in {{ $labels.source_cluster }}
          description: >-
            API Server process memory consumption is above 80% for 5 minutes in cluster {{ $labels.source_cluster }}.
          alert_team_handle: <!subteam^S05Q1P4Q2TG>
          team: konflux-infra
          runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/infra/sre/apiserver_HighMemoryUsage.md
