apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-velero-alerting
  labels:
    tenant: rhtap
spec:
  groups:
    - name: velero_alerts
      interval: 1m
      rules:

      - alert: VeleroBackupNeverStarted
        expr: |
          kube_customresource_velero_schedule_last_backup == 0
        for: 5h
        labels:
          severity: high
          component: velero
        annotations:
          summary: >-
            Velero backup has never started
          description: >-
            Velero schedule {{ $labels.schedule }} has never started a backup in cluster {{ $labels.source_cluster }}.
          alert_routing_key: infra
          team: konflux-infra
          runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/infra/disaster-recovery/cluster/tenants-backup-and-restore/observability.md
