apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-etcd-defrag-alerting
  labels:
    tenant: rhtap
spec:
  groups:
    - name: etcd_defrag_alerts
      interval: 1m
      rules:

      - alert: EtcdDefragFrequent
        expr: |
          sum by (source_cluster) (etcd_disk_defrag_inflight) > 0
          and
          sum by (source_cluster) (max_over_time(etcd_disk_defrag_inflight[20m] offset 10m)) > 0
        for: 1m
        labels:
          severity: high
          component: etcd
        annotations:
          summary: >-
            Etcd defragmentation is happening too frequently
          description: >-
            Etcd defragmentation occurred more than once in the last 30 minutes in cluster {{ $labels.source_cluster }}.
          alert_routing_key: infra
          team: konflux-infra
          runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/infra/etcd.md
