apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-pv-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: pv_alerts
    interval: 1m
    rules:
    - alert: PersistentVolumeIssues
      expr: kube_persistentvolume_status_phase{phase=~"Failed|Pending", namespace!~"(.*-tenant|.*-env|openshift-.*|kube-.*|default|tekton-ci|build-templates-e2e)"} == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: >-
          Persistent Volume {{ $labels.persistentvolume }} is in {{ $labels.phase }} phase for more than 5 minutes.
        description: >-
          Persistent Volume {{ $labels.persistentvolume }} in namespace {{ $labels.namespace }} on cluster {{ $labels.source_cluster }}
          is in {{ $labels.phase }} phase for more than 5 minutes.
        alert_routing_key: '{{ $labels.namespace }}'
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/o11y/alert-rule-pesistentVolumeIssues.md
