apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-release-service-alerting
  labels:
    tenant: rhtap
spec:
  groups:
  - name: release_service_alerts
    interval: 1m

    rules:
    - alert: ReleaseServiceControllerManagerPodNotReady
      expr: |
        sum by (source_cluster, namespace) (kube_pod_container_status_ready{container="manager",namespace="release-service",source_cluster=~"stone-prd-rh01|stone-prod-p02"}) == 0
      for: 10m
      labels:
        severity: high
        component: release-service
      annotations:
        summary: >-
          The Release Service Controller Manager is down in the {{ $labels.source_cluster }} for the last 10 minutes
        description: >-
          The Release Service Controller Manager is down in the {{ $labels.source_cluster }} for the last 10 minutes
        alert_routing_key: "{{ $labels.namespace }}"
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/release-service/release-controller-availability.md?ref_type=heads
        team: release

    - alert: ReleaseServiceControllerManagerDown
      expr: |
        konflux_up{
          check="replicas-available",
          service="release-service-controller-manager"
        } != 1
      for: 10m
      labels:
        severity: critical
        slo: "true"
        component: release-service
      annotations:
        html_url: https://github.com/redhat-appstudio/o11y/blob/main/rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml#L36
        summary: >-
          Release Service Controller Manager pod is down in cluster {{ $labels.source_cluster }}
        description: >
          Release Service Controller Manager pod has been down for 10 minutes in cluster {{ $labels.source_cluster }}
        alert_team_handle: <!subteam^S03SVBS426R>
        team: release
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/release-service/release-controller-availability.md?ref_type=heads
