apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-kyverno-alerting-rules
  labels:
    tenant: rhtap

spec:
  groups:
    - name: kyverno-unavailable
      interval: 1m
      rules:
      - alert: KyvernoDeploymentDown
        expr: |
          kube_deployment_spec_replicas{namespace="konflux-kyverno"} * 3 != kube_deployment_status_replicas * 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: kyverno has reported that not all the deployments pods are up and running 5 minutes
          description: "kyverno on cluster '{{ $labels.source_cluster }}' has that not all the deployments pods are up and running for 5 minutes"
          alert_team_handle: <!subteam^S05Q1P4Q2TG>
          team: konflux-infra