apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-integration-service-availability-slo-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
    - name: integration-service-availability-slo
      interval: 1m
      rules:
        - alert: IntegrationServiceAvailabilitySLOViolation
          expr: |
            konflux_up{
              namespace="integration-service",
              check="replicas-available"
            } != 1
          for: 5m
          labels:
            severity: critical
            slo: "true"
            tenant: rhtap
          annotations:
            summary: >-
              Integration Service Availability SLO Violation
            description: >-
              Integration service '{{ $labels.service }}' in namespace '{{ $labels.namespace }}' on {{ $labels.source_cluster }} has been down for 5min.
            alert_team_handle: <!subteam^S05M4AG8CJH>
            team: integration
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/integration-service/sre/integration_service_availability_replicas_available.md
