apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-gitops-statefulsets-alerting
  labels:
    tenant: rhtap
spec:
  groups:
  - name: gitops_statefulsets_alerts
    interval: 1m
    rules:
    - alert: GitOpsStatefulSetsHealthErrors
      expr: |
        (
          sum(kube_statefulset_status_replicas_ready{namespace="gitops-service-argocd"})
          by (source_cluster)
        )
        /
        (
          sum(kube_statefulset_replicas{namespace="gitops-service-argocd"})
          by (source_cluster)
        ) < 0.95
      for: 5m
      labels:
        severity: warning
        slo: "true"
      annotations:
        summary: >-
          Less than 95% of GitOps StatefulSets are in Healthy state: {{ $value | humanizePercentage }} in cluster: {{ $labels.source_cluster }}
        description: >-
          The percentage total of Argo CD StatefulSets that are in Healthy state is less than 95% in cluster: {{ $labels.source_cluster }}.
        runbook_url: https://gitlab.cee.redhat.com/rhtap/docs/sop/-/blob/main/gitops/statefulsets.md
