apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-pulp-release-pipeline-alerting
  labels:
    tenant: rhtap
spec:
  groups:
  - name: pulp_release_pipeline_alerts
    interval: 1m

    rules:
    - alert: ReleaseTaskOOMKilled
      expr: |
        count by (source_cluster,namespace,container,pod) (kube_pod_container_status_terminated_reason{reason="OOMKilled",namespace=~".*-tenant",pod=~".*(push-rpms-to-pulp|push-rpm-data-to-pyxis|upload-src-rpm-sbom-attestation).*"}) >= 1
      for: 5m
      labels:
        severity: high
        slo: "false"
        component: release-service
      annotations:
        summary: >-
          RPM release task OOMKilled in {{ $labels.namespace }} on {{ $labels.source_cluster }}
        description: >-
          An RPM release pipeline container (push-rpms-to-pulp, push-rpm-data-to-pyxis, or
          upload-src-rpm-sbom-attestation) was OOMKilled in namespace {{ $labels.namespace }}
          on cluster {{ $labels.source_cluster }}.
        alert_routing_key: release-service
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/release-service/sre/rpm-release-pipeline-troubleshooting.md
        team: release
