apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-api-server-availability
  labels:
    tenant: rhtap

spec:
  groups:
    - name: api_server_service_availability
      interval: 1m
      rules:
        - record: konflux_up
          expr: |
            label_replace(
              (
                sum by(source_cluster) (
                  code:apiserver_request_total:rate5m{code=~"5.."}
                ) /
                sum by(source_cluster) (
                  code:apiserver_request_total:rate5m{code!="0"}
                )
                OR on(source_cluster) vector(0.000001)
              ) * 100, "service", "api-server", "", ""
            )
            <= bool 5
          labels:
            service: api-server

        - record: api_server:error_rate_10m
          expr: |
            (
              sum by(source_cluster) (
                rate(apiserver_request_total{code=~"5..|4.."}[10m])
              ) /
              sum by(source_cluster) (
                rate(apiserver_request_total{code!="0"}[10m])
              )
            ) * 100
          labels:
            service: api-server

        - record: api_server:error_rate_30d_avg
          expr: |
            avg_over_time(api_server:error_rate_10m[30d])
          labels:
            service: api-server

        - record: api_server:error_rate_30d_stddev
          expr: |
            stddev_over_time(api_server:error_rate_10m[30d])
          labels:
            service: api-server

