apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-otp-service-availability
  labels:
    tenant: rhtap
spec:
  groups:
    - name: otp_deployment_service_availability
      interval: 1m
      rules:
        - record: konflux_up
          expr: |
            clamp_max(
              label_replace(
                label_replace(
                  floor(
                    kube_deployment_status_replicas_available{
                      namespace="multi-platform-controller", deployment="multi-platform-otp-server"
                    } / kube_deployment_spec_replicas
                  ), "check", "replicas-available", "",""
                ), "service", "$1", "deployment","(.*)"
              ), 1
            )
