apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-project-controller-availability
  labels:
    tenant: rhtap
spec:
  groups:
    - name: project_controller_availability
      interval: 1m
      rules:
        # recorded value: 0 if spec is higher than available, 1 otherwise
        # labels: check=replicas-available, service=<deployment-name>
        - record: konflux_up
          expr: |
            clamp_max(
              label_replace(
                label_replace(
                  floor(
                    kube_deployment_status_replicas_available{
                      namespace="project-controller"
                    } / kube_deployment_spec_replicas
                  ), "check", "replicas-available", "",""
                ), "service", "$1", "deployment","(.*)"
              ), 1
            )
          labels:
            service: project-controller
