{
 "title": "Availability exporter dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(konflux_up,service)"
    }
   },
   {
    "name": "check",
    "query": {
     "query": "label_values(konflux_up{service=~\"$service\"},check)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability percentage",
   "type": "gauge",
   "description": "This gauge shows the system's overall availability percentage, indicating how often services are operational and available.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum_over_time((konflux_up{service=~\"$service\"} == 1)[$__range:]) * 100 / sum_over_time(konflux_up{service=~\"$service\"}[$__range:]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Healthy service instances",
   "type": "stat",
   "description": "This panel displays the current count of healthy instances of services within the system. It updates dynamically to reflect the real-time health of services.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( sum by (service, check) (konflux_up{service=~\"$service\"} == 1))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Degraded service instances",
   "type": "stat",
   "description": "This panel shows the number of services currently experiencing degraded performance within the system. It dynamically updates to indicate services that are not operating at full capacity.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( sum by (service, check) (konflux_up{service=~\"$service\"} == 0))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Availability probe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Individual availability probes",
   "type": "timeseries",
   "description": "This line graph illustrates the operational status of different service components within a given time range. This panel provides real-time visualization of uptime percentages for each distinct service and overall services, enabling users to monitor the reliability and availability of individual service components.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(group by (service, check, source_cluster) (count_over_time((konflux_up{service=~\"$service\", check=~\"$check\"} == 1)[$__range:])) / group by (service, check, source_cluster) (count_over_time(konflux_up{service=~\"$service\", check=~\"$check\"}[$__range:])) ) * 100",
     "legendFormat": "{{source_cluster}} - {{service}} - {{check}} "
    }
   ]
  }
 ]
}