{
 "title": "Konflux Tenant-Level UX Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kueue_admission_wait_time_seconds_sum,source_cluster)"
    }
   },
   {
    "name": "Tenant",
    "query": {
     "query": "label_values(kube_namespace_labels{source_cluster=~\"$Cluster\"},namespace)"
    }
   },
   {
    "name": "omit_tenant",
    "label": "Omitted Tenants",
    "query": "dev-release-team-tenant, konflux-perfscale-1-tenant, konflux-perfscale-2-tenant, konflux-perfscale-3-tenant, konflux-perfscale-4-tenant , konflux-perfscale-5-tenant, konflux-perfscale-6-tenant"
   }
  ]
 },
 "panels": [
  {
   "title": "Tenant-Level Metrics - ${Tenant}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Tenant",
   "collapsed": true,
   "panels": [
    {
     "title": "30-day Average Times for Builds by Component",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    avg by (source_cluster, exported_namespace, application, component) (konflux_build_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    avg by (source_cluster, exported_namespace, application, component) (konflux_build_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rates for Builds by Component",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_build_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_build_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n  (\n    sum by (source_cluster, application, component) (\n      konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", event_type=~\"retest-comment|retest-all-comment\"}\n    ) \n    or \n    sum by (source_cluster, application, component) (\n      konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}\n    ) * 0\n  )\n  /\n  sum by (source_cluster, application, component) (\n    konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "30-day Average Times for Integrations (Tests) by Scenario",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    avg by (source_cluster, exported_namespace, application, component, scenario, test_type) (konflux_integration_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    avg by (source_cluster, exported_namespace, application, component, scenario, test_type) (konflux_integration_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rates for Integrations (Tests) by Scenario",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n        or \n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n        or \n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n  (\n    sum by (source_cluster, application, component, scenario, test_type) (\n      konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", event_type=~\"retest-comment|retest-all-comment\"}\n    ) \n    or \n    sum by (source_cluster, application, component, scenario, test_type) (\n      konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}\n    ) * 0\n  )\n  /\n  sum by (source_cluster, application, component, scenario, test_type) (\n    konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "30-day Average Times for Releases by Component",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    avg by (source_cluster, exported_namespace, application, component) (konflux_release_cr_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    avg by (source_cluster, exported_namespace, application, component) (konflux_release_cr_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rates for Releases by Component",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_release_cr_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_release_cr_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n  (\n    sum by (source_cluster, application, component) (\n      konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", event_type=~\"retest-comment|retest-all-comment\"}\n    ) \n    or \n    sum by (source_cluster, application, component) (\n      konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}\n    ) * 0\n  )\n  /\n  sum by (source_cluster, application, component) (\n    konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\"}\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Tenant-Level Metrics - Overall for Builds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Tenants - 30-day Average Build Time",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 740 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    topk (10,\n        topk by (exported_namespace) (1, konflux_build_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    )\n)",
       "legendFormat": "{{exported_namespace}} - {{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Top 10 Tenants - 30-day Average Build Wait Time",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 740 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    topk (10,\n        topk by (exported_namespace) (1, konflux_build_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"} > 0)\n    )\n)",
       "legendFormat": "{{exported_namespace}} - {{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Distribution of 30-day Average Build Time",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 820 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (application, component) (konflux_build_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Distribution of 30-day Average Build Wait Time",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 820 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (application, component) (konflux_build_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Tenants with Partial Build Success Rates",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 827 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    1 > (\n        sum by (source_cluster, exported_namespace) (konflux_build_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n        /\n        sum by (source_cluster, exported_namespace) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    ) > 0\n)",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Tenants with 0% Build Success Rates",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 827 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, exported_namespace) (konflux_build_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n        / \n        sum by (source_cluster, exported_namespace) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    ) == 0\n)",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Tenants with Build Failure Rates (>0%)",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 834 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        (\n            sum by (source_cluster, exported_namespace) (konflux_build_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n            or \n            sum by (source_cluster, exported_namespace) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"}) * 0\n        )\n        /\n        sum by (source_cluster, exported_namespace) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    ) > 0\n)",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Tenants with Build Retry Rates (>0%)",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 834 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, exported_namespace) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", event_type=~\"retest-comment|retest-all-comment\"})\n        /\n        sum by (source_cluster, exported_namespace) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    ) > 0\n)",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Total Build Throughput (30d)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 841 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(konflux_build_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"})"
      }
     ]
    },
    {
     "title": "Build Volume by Tenant (30d rolling count)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 841 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exported_namespace) (konflux_build_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"})",
       "legendFormat": "{{exported_namespace}}"
      }
     ]
    },
    {
     "title": "Top 10 Tenants by Build Volume",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 848 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum by (exported_namespace) (konflux_build_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"}))",
       "legendFormat": "{{exported_namespace}}"
      }
     ]
    },
    {
     "title": "Top 5 Build Failure Reasons",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 848 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (reason) (konflux_build_failure_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"}))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Build Daily Throughput Rate (total_count/30)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 856 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exported_namespace) (konflux_build_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"}) / 30",
       "legendFormat": "{{exported_namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tenant-Level Metrics - Overall for Integrations (Tests)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 190 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Tenants - 30-day Average Integration (Test) Time",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    topk (10,\n        topk by (exported_namespace) (1, konflux_integration_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    )\n)",
       "legendFormat": "{{exported_namespace}} - {{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Top 10 Tenants - 30-day Average Integration (Test) Wait Time",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    topk (10,\n        topk by (exported_namespace) (1, konflux_integration_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"} > 0)\n    )\n)",
       "legendFormat": "{{exported_namespace}} - {{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Distribution of 30-day Average Integration (Test) Time",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (application, component) (konflux_integration_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Distribution of 30-day Average Integration (Test) Wait Time",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (application, component) (konflux_integration_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Tenants with Partial Integration (Test) Success Rates",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    1 > (\n        sum by (source_cluster, exported_namespace) (konflux_integration_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n        /\n        sum by (source_cluster, exported_namespace) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    ) > 0\n)",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Tenants with 0% Integration (Test) Success Rates",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, exported_namespace) (konflux_integration_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n        / \n        sum by (source_cluster, exported_namespace) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    ) == 0\n)",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Tenants with EC Integration (Test) Failure Rates (>0%)",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        (\n            sum by (source_cluster, exported_namespace, test_type) (konflux_integration_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", test_type=\"ec\"})\n            or \n            sum by (source_cluster, exported_namespace, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", test_type=\"ec\"}) * 0\n        )\n        /\n        sum by (source_cluster, exported_namespace, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", test_type=\"ec\"})\n    ) > 0\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tenants with EC Integration (Test) Retry Rates (>0%)",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, exported_namespace, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", event_type=~\"retest-comment|retest-all-comment\", test_type=\"ec\"})\n        /\n        sum by (source_cluster, exported_namespace, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", test_type=\"ec\"})\n    ) > 0\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tenants with Non-EC Integration (Test) Failure Rates (>0%)",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        (\n            sum by (source_cluster, exported_namespace, test_type) (konflux_integration_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", test_type!=\"ec\"})\n            or \n            sum by (source_cluster, exported_namespace, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", test_type!=\"ec\"}) * 0\n        )\n        /\n        sum by (source_cluster, exported_namespace, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", test_type!=\"ec\"})\n    ) > 0\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tenants with Non-EC Integration (Test) Retry Rates (>0%)",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, exported_namespace, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", event_type=~\"retest-comment|retest-all-comment\", test_type!=\"ec\"})\n        /\n        sum by (source_cluster, exported_namespace, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", test_type!=\"ec\"})\n    ) > 0\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Integration Throughput (30d)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 231 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(konflux_integration_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"})"
      }
     ]
    },
    {
     "title": "Integration Test Volume by Tenant (30d rolling count)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 231 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exported_namespace) (konflux_integration_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"})",
       "legendFormat": "{{exported_namespace}}"
      }
     ]
    },
    {
     "title": "Top 10 Tenants by Integration Test Volume",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 238 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum by (exported_namespace) (konflux_integration_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"}))",
       "legendFormat": "{{exported_namespace}}"
      }
     ]
    },
    {
     "title": "Top 5 Integration Failure Reasons",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 238 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (reason) (konflux_integration_failure_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"}))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Integration Daily Throughput Rate (total_count/30)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exported_namespace) (konflux_integration_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"}) / 30",
       "legendFormat": "{{exported_namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tenant-Level Metrics - Overall for Releases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 191 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Tenants - 30-day Average Release Time",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 272 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    topk (10,\n        topk by (exported_namespace) (1, konflux_release_cr_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Tenants - 30-day Average Release Wait Time",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 272 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    topk (10,\n        topk by (exported_namespace) (1, konflux_release_cr_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"} > 0)\n    )\n)",
       "legendFormat": "{{exported_namespace}} - {{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Distribution of 30-day Average Release Time",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 284 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (application, component) (konflux_release_cr_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Distribution of 30-day Average Release Wait Time",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 284 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (application, component) (konflux_release_cr_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Tenants with Partial Release Success Rates",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 291 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    1 > (\n        sum by (source_cluster, exported_namespace) (konflux_release_cr_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n        /\n        sum by (source_cluster, exported_namespace) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    ) > 0\n)",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Tenants with 0% Release Success Rates",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 291 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, exported_namespace) (konflux_release_cr_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n        / \n        sum by (source_cluster, exported_namespace) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    ) == 0\n)",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Tenants with Release Failure Rates (>0%)",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        (\n            sum by (source_cluster, exported_namespace) (konflux_release_cr_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n            or \n            sum by (source_cluster, exported_namespace) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"}) * 0\n        )\n        /\n        sum by (source_cluster, exported_namespace) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    ) > 0\n)",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Tenants with Release Retry Rates (>0%)",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, exported_namespace) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\", event_type=~\"retest-comment|retest-all-comment\"})\n        /\n        sum by (source_cluster, exported_namespace) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace!~\"${omit_tenant}\"})\n    ) > 0\n)",
       "legendFormat": "{{application}} - {{component}}"
      }
     ]
    },
    {
     "title": "Total Release Throughput (30d)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(konflux_release_cr_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"})"
      }
     ]
    },
    {
     "title": "Release Automation Adoption %",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(konflux_release_cr_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\", automated=\"true\"}) / sum(konflux_release_cr_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"})"
      }
     ]
    },
    {
     "title": "Automated vs. Manual Releases",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (automated) (konflux_release_cr_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"})",
       "legendFormat": "{{automated}}"
      }
     ]
    },
    {
     "title": "Release Volume by Tenant (30d rolling count)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 311 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exported_namespace) (konflux_release_cr_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"})",
       "legendFormat": "{{exported_namespace}}"
      }
     ]
    },
    {
     "title": "Top 10 Tenants by Release Volume",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 318 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum by (exported_namespace) (konflux_release_cr_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"}))",
       "legendFormat": "{{exported_namespace}}"
      }
     ]
    },
    {
     "title": "Top 5 Release Failure Reasons",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 318 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (reason) (konflux_release_cr_failure_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"}))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Release Daily Throughput Rate (total_count/30)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 326 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exported_namespace) (konflux_release_cr_total_count_30d{source_cluster=~\"${Cluster}\", exported_namespace!~\"${omit_tenant}\"}) / 30",
       "legendFormat": "{{exported_namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster-Level Kueue Metrics - ${Cluster}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 192 },
   "repeat": "Cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "${Cluster} - Kueue Admission Wait Time Averages by Priority Class",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2205 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kueue_admission_wait_time_seconds_sum{source_cluster=~\"${Cluster}\"} / kueue_admission_wait_time_seconds_count{source_cluster=~\"${Cluster}\"}",
       "legendFormat": "{{priority_class}}"
      }
     ]
    },
    {
     "title": "${Cluster} - Kueue Admission Wait Time P99 by Priority Class",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2205 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kueue_admission_wait_time_seconds_bucket{source_cluster=~\"${Cluster}\"}[$__range])) by (priority_class, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${Cluster} - Kueue Admission Wait Time Averages by Priority Class - Time Chart",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2211 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kueue_admission_wait_time_seconds_sum{source_cluster=~\"${Cluster}\"} / kueue_admission_wait_time_seconds_count{source_cluster=~\"${Cluster}\"}",
       "legendFormat": "{{priority_class}}"
      }
     ]
    },
    {
     "title": "${Cluster} - Kueue Resource Usages",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2218 },
     "targets": [
      {
       "expr": "sort_desc(max by (resource) (kueue_cluster_queue_resource_usage{source_cluster=~\"${Cluster}\"} / kueue_cluster_queue_nominal_quota{source_cluster=~\"${Cluster}\"}))",
       "legendFormat": "{{resource}}"
      },
      {
       "expr": " max by (resource) (kueue_cluster_queue_resource_usage{source_cluster=~\"${Cluster}\"})",
       "legendFormat": "{{resource}}"
      },
      {
       "expr": "max by (resource) (kueue_cluster_queue_nominal_quota{source_cluster=~\"${Cluster}\"})",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "${Cluster} - Kueue Resource Usages - Time Chart",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2225 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by (resource) (kueue_cluster_queue_resource_usage{source_cluster=~\"${Cluster}\"} / kueue_cluster_queue_nominal_quota{source_cluster=~\"${Cluster}\"})",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  }
 ]
}