{
 "title": "KubeArchive Status",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "See the [KubeArchive SLO dashboard](/d/beqtfn88x35kwd/kubearchive-slos)\n\n*This dashboard may show incorrect results due to changes\nrequired in the o11y side from Konflux. Don't trust what\nyou see here and go to the Grafana instance in each of the\ncluster*\n\nThis dashboard is meant to be used with one cluster\nat a time. Please select a single cluster from\nthe Cluster dropdown just above this text. Check\n[Eran's aggregator page](https://konflux.pages.redhat.com/konflux-portal/developer/konflux-clusters.html)\nfor links of all the clusters.\n\n"
   }
  },
  { "title": "General health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Konflux UP Metric",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "konflux_up{source_cluster=~\"$cluster\", service=~\"kubearchive-.*\"}",
     "legendFormat": "{{ source_cluster }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Konflux UP Metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "konflux_up{source_cluster=~\"$cluster\", service=~\"kubearchive-.*\"}",
     "legendFormat": "{{ source_cluster }} - {{ service }}"
    }
   ]
  },
  {
   "title": "PipelineRuns on the cluster",
   "type": "timeseries",
   "description": "The two lines shouldn't be perfectly align, as this Tekton metric is is not PipelineRun creation, but pipelines in the cluster, so they are not comparable with ours. However an increase in one should mean an increase int he other.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (source_cluster) (increase(tekton_pipelines_controller_pipelinerun_total{source_cluster=~\"$cluster\"}[1h]))",
     "legendFormat": "{{source_cluster }} - PipelineRuns"
    },
    {
     "expr": "sum by (source_cluster) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", resource_type=\"tekton.dev/v1/PipelineRun\", result=\"insert\"}[1h]))",
     "legendFormat": "{{source_cluster }} -  PipelineRun CE Received"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memory_used{source_cluster=~\"$cluster\"}",
     "legendFormat": "{{ source_cluster }} - {{ exported_job }}"
    }
   ]
  },
  {
   "title": "API latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (http_status_code, source_cluster)(rate(http_server_request_duration_sum{source_cluster=~\"$cluster\",exported_job=\"kubearchive.api\", http_route!~\"(/livez|/readyz)\"}[$__rate_interval]))/sum by (http_status_code, source_cluster)(rate(http_server_request_duration_count{source_cluster=~\"$cluster\",exported_job=\"kubearchive.api\", http_route!~\"(/livez|/readyz)\"}[$__rate_interval]))",
     "legendFormat": "{{ source_cluster }} - {{ http_status_code }}"
    }
   ]
  },
  {
   "title": "Sink latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (http_status_code, source_cluster)(rate(http_server_request_duration_sum{source_cluster=~\"$cluster\",exported_job=\"kubearchive.sink\", http_route!~\"(/livez|/readyz)\"}[$__rate_interval]))/sum by (http_status_code, source_cluster)(rate(http_server_request_duration_count{source_cluster=~\"$cluster\",exported_job=\"kubearchive.sink\", http_route!~\"(/livez|/readyz)\"}[$__rate_interval]))",
     "legendFormat": "{{ source_cluster }} - {{ http_status_code }}"
    }
   ]
  },
  { "title": "DB statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "API DB latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (rate(db_sql_latency_sum{source_cluster=~\"$cluster\", exported_job=\"kubearchive.api\", method!~\".*(ping|reset_session)\"}[$__rate_interval])) / sum by (source_cluster) (rate(db_sql_latency_count{source_cluster=~\"$cluster\", exported_job=\"kubearchive.api\", method!~\".*(ping|reset_session)\"}[$__rate_interval]))",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Sink DB latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (rate(db_sql_latency_sum{source_cluster=~\"$cluster\", exported_job=\"kubearchive.sink\", method!~\".*(ping|reset_session)\"}[$__rate_interval])) / sum by (source_cluster) (rate(db_sql_latency_count{source_cluster=~\"$cluster\", exported_job=\"kubearchive.sink\", method!~\".*(ping|reset_session)\"}[$__rate_interval]))",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "DB connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "db_sql_connection_open{source_cluster=~\"$cluster\"}",
     "legendFormat": "{{ source_cluster }} - {{ status }} - {{ exported_job }}"
    }
   ]
  },
  {
   "title": "Rate Error CloudEvents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 38 },
   "targets": [
    {
     "expr": "sum by (resource_type) (rate(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", result=\"error\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cloud Events Increases 1 hour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "All CloudEvents - 1 hour increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (resource_type) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No Conf CloudEvents - 1 hour increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 47 },
   "targets": [
    {
     "expr": "sum by (resource_type) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", result=\"no_conf\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insert CloudEvents - 1 hour increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by (resource_type) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", result=\"insert\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No Match CloudEvents - 1 hour increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 55 },
   "targets": [
    {
     "expr": "sum by (resource_type) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", result=\"no_match\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update CloudEvents - 1 hour increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by (resource_type) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", result=\"update\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error CloudEvents - 1 hour increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 63 },
   "targets": [
    {
     "expr": "sum by (resource_type) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", result=\"error\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}