{
 "title": "Konflux - Kyverno",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Building blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Latest Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Unequal Deployment Replicas",
   "type": "timeseries",
   "description": "Displays the count of deployments in the konflux-kyverno namespace where the desired number of replicas does not match the actual ready replicas.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"konflux-kyverno\"} != kube_deployment_status_replicas_ready{namespace=\"konflux-kyverno\"}"
    }
   ]
  },
  {
   "title": "Cluster Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total==1) by (source_cluster))"
    }
   ]
  },
  {
   "title": "Generate Rules",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"generate\"}==1) by (rule_name)"
    }
   ]
  },
  {
   "title": "Background Scans Failure Rate (Last 24 Hours)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_result=\"fail\", policy_background_mode=\"true\"}[24h]) or vector(0))*100/sum(increase(kyverno_policy_results_total{policy_background_mode=\"true\"}[24h]))"
    }
   ]
  },
  {
   "title": "Validate Rules",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"validate\"}==1) by (rule_name)"
    }
   ]
  },
  {
   "title": "Rule Execution Failure Rate (Last 24 Hours)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_result=\"fail\"}[24h]) or vector(0))*100/sum(increase(kyverno_policy_results_total[24h]))"
    }
   ]
  },
  { "title": "Policy-Rule Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Admission Review Results (per-rule)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}[5m])) by (rule_result)",
     "legendFormat": "Admission Review Result: {{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-rule)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_execution_cause=\"background_scan\"}[5m])) by (rule_result)",
     "legendFormat": "Background Scan Result: {{rule_result}}"
    }
   ]
  },
  {
   "title": "Policy Failures",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (policy_type) (\n  sum by (policy_name, policy_type) (\n    increase(kyverno_policy_results_total{rule_result=\"fail\"}[5m])\n  )\n)\nOR\nsum by (policy_type) (\n  kyverno_policy_results_total * 0\n)",
     "legendFormat": "Policy Type: {{policy_type}}"
    }
   ]
  },
  {
   "title": "Admission Review Results (per-policy)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(increase(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}[5m])) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "Admission Review Result: {{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-policy)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(increase(kyverno_policy_results_total{rule_execution_cause=\"background_scan\"}[5m])) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "Background Scan Result: {{rule_result}}"
    }
   ]
  },
  { "title": "Policy-Rule Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Active Policies (by policy type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total==1) by (policy_name))",
     "legendFormat": "Policy Type: {{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Policies (by policy validation action)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total==1) by (policy_name, policy_validation_mode)) by (policy_validation_mode)",
     "legendFormat": "Policy Validation Mode: {{policy_validation_mode}}"
    }
   ]
  },
  {
   "title": "Active Rules (by rule type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total==1) by (rule_type, rule_name)",
     "legendFormat": "Rule Type: {{rule_type}}"
    }
   ]
  },
  {
   "title": "Active Policies running in background mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_background_mode=\"true\"}==1) by (policy_name, policy_type))",
     "legendFormat": "Policy Type: {{policy_type}}"
    }
   ]
  },
  { "title": "Policy-Rule Execution Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Average Rule Execution Latency Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_policy_execution_duration_seconds_sum[5m])) by (rule_type) / sum(rate(kyverno_policy_execution_duration_seconds_count[5m])) by (rule_type)",
     "legendFormat": "Rule Type: {{rule_type}}"
    }
   ]
  },
  {
   "title": "Average Policy Execution Latency Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_policy_execution_duration_seconds_sum[5m])) by (policy_type) / sum(rate(kyverno_policy_execution_duration_seconds_count[5m])) by (policy_type)",
     "legendFormat": "Policy Type: {{policy_type}}"
    }
   ]
  },
  {
   "title": "Overall Average Rule Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_execution_duration_seconds_sum) / sum(kyverno_policy_execution_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Overall Average Policy Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kyverno_policy_execution_duration_seconds_sum) by (policy_name, policy_type) / sum(kyverno_policy_execution_duration_seconds_count) by (policy_name, policy_type))"
    }
   ]
  },
  { "title": "Admission Review Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Avg - Admission Review Duration Over Time (by operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_review_duration_seconds_sum[5m])) by (resource_request_operation) / sum(rate(kyverno_admission_review_duration_seconds_count[5m])) by (resource_request_operation)",
     "legendFormat": "Resource Operation: {{resource_request_operation}}"
    }
   ]
  },
  {
   "title": "Avg - Admission Review Duration Over Time (by resource kind)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_review_duration_seconds_sum[5m])) by (resource_kind) / sum(rate(kyverno_admission_review_duration_seconds_count[5m])) by (resource_kind)",
     "legendFormat": "Resource Kind: {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Rate - Incoming Admission Requests (per 5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Avg - Overall Admission Review Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_admission_review_duration_seconds_sum)/sum(kyverno_admission_review_duration_seconds_count)"
    }
   ]
  },
  { "title": "Policy Changes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Policy Changes Over Time (by change type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(policy_change_type) (increase(kyverno_policy_changes_total[5m]))",
     "legendFormat": "Change type: {{policy_change_type}}"
    }
   ]
  },
  {
   "title": "Policy Changes Over Time (by policy type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_changes_total[5m])) by (policy_type)",
     "legendFormat": "Policy Type: {{policy_type}}"
    }
   ]
  },
  {
   "title": "Total Policy Changes (Last 24 Hours)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_changes_total[24h]))"
    }
   ]
  },
  {
   "title": "Rate - Policy Changes Happening (last 5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_policy_changes_total[5m]))"
    }
   ]
  },
  { "title": "Admission Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Admission Requests (by operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total[5m])) by (resource_request_operation)",
     "legendFormat": "Resource Operation: {{resource_request_operation}}"
    }
   ]
  },
  {
   "title": "Admission Requests (by resource kind)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total[5m])) by (resource_kind)",
     "legendFormat": "Resource Kind: {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Total Admission Requests (Last 24 Hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total[24h]))"
    }
   ]
  }
 ]
}