{
 "title": "Konflux Alerts Activity",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Select Cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "SLO Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alert list Overall (firing/Pending) Production",
     "type": "alertlist",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 }
    },
    {
     "title": "Alert Rate (firing)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "count by (alertname) (rate(ALERTS{source_cluster=~\"$cluster\",alertstate=\"firing\", slo=\"true\"}[$__range]))",
       "legendFormat": "{{severity}}"
      }
     ]
    },
    {
     "title": "Alert rate (Pending)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "count by (alertname) (rate(ALERTS{source_cluster=~\"$cluster\",alertstate=\"pending\", slo=\"true\"}[$__range]))",
       "legendFormat": "{{severity}}"
      }
     ]
    },
    {
     "title": "Alerts Firing state count ",
     "type": "stat",
     "description": "total number of alerts that are currently in the firing state",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (alertname) (increase(ALERTS{source_cluster=~\"$cluster\", alertstate=\"firing\", slo=\"true\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Alerts Pending state count",
     "type": "stat",
     "description": "To see alerts that have breached their condition but haven't been firing for long enough to trigger a notification, you can query for alerts in the pending state. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (alertname) (increase(ALERTS{source_cluster=~\"$cluster\", alertstate=\"pending\", slo=\"true\"}[$__range]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts Firing state",
     "type": "timeseries",
     "description": "total number of alerts that are currently in the firing state",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "count by (alertname)(ALERTS{source_cluster=~\"$cluster\",alertstate=\"firing\", slo!=\"true\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Alerts Pending state",
     "type": "timeseries",
     "description": "To see alerts that have breached their condition but haven't been firing for long enough to trigger a notification, you can query for alerts in the pending state. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "count by (alertname)(ALERTS{source_cluster=~\"$cluster\", slo!=\"true\", alertstate=\"pending\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Alerts Firing Rate",
     "type": "timeseries",
     "description": "total number of alerts that are currently in the firing state",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "count by (alertname) (rate(ALERTS{source_cluster=~\"$cluster\", slo!=\"true\", alertstate=\"firing\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top  Frequent Firing Alerts ",
     "type": "bargauge",
     "description": "Top frequent alerts",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, count(ALERTS{alertstate=\"firing\", slo!=\"true\", source_cluster=~\"$cluster\"}) by (alertname))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Alert state count (firing)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (severity) (ALERTS{alertstate=\"firing\", slo!=\"true\", source_cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Alert state count (pending)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (severity) (ALERTS{alertstate=\"pending\", slo!=\"true\", source_cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Alerts (Pending/Firing) overtime",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "count(ALERTS{source_cluster=~\"$cluster\", slo!=\"true\", alertstate=\"firing\"}) by (alertstate)",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(ALERTS{source_cluster=~\"$cluster\", slo!=\"true\", alertstate=\"pending\"}) by (alertstate)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}