{
 "title": "API Server Activity",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Select Cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, source_cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Konflux Up Availability Signal",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(count_over_time((konflux_up{service=~\"api-server\", source_cluster=~\"$cluster\"} == 1)[$__range:]) / count_over_time(konflux_up{service=~\"api-server\", source_cluster=~\"$cluster\"}[$__range:])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "barchart",
   "description": "A sudden spike or sustained high number might indicate a bottleneck or a hanging request, impacting responsiveness.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests{source_cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU & Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage by Cluster - API Server Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (source_cluster) (rate(process_cpu_seconds_total{job=\"apiserver\", source_cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Instance  - API Server Job",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg by (instance,source_cluster) (rate(process_cpu_seconds_total{job=\"apiserver\", source_cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{source_cluster}} : {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Cluster - API Server Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(process_resident_memory_bytes{job=\"apiserver\", source_cluster=~\"$cluster\"}) by (source_cluster)\n/\n  sum(node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"}) by (source_cluster)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Instance  (API Server Job)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (instance, source_cluster) (avg_over_time(process_resident_memory_bytes{job=\"apiserver\", source_cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{source_cluster}} : {{instance}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "P95 Latency by Verb",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum by (le, verb) (\n      rate(verb:apiserver_request_duration_seconds_bucket:rate5m{source_cluster=~\"$cluster\"}[5m])\n    )\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (le) (histogram_quantile(0.95, verb:apiserver_request_duration_seconds_bucket:rate5m{source_cluster=~\"$cluster\"}\n))",
     "legendFormat": "P95 Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum without (verb) (verb:apiserver_request_duration_seconds_bucket:rate5m{source_cluster=~\"$cluster\"}\n))",
     "legendFormat": "Overall Latency"
    }
   ]
  },
  { "title": "API Requests Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "API Server Request Rate by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "instance:apiserver_request_total:rate5m{source_cluster=~\"$cluster\"}",
     "legendFormat": "{{source_cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "API Server Request Rate by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(code:apiserver_request_total:rate5m{code=~\"2..\", source_cluster=~\"$cluster\"})",
     "legendFormat": "HTTP 2XX "
    },
    {
     "expr": "sum(code:apiserver_request_total:rate5m{code=~\"3..\", source_cluster=~\"$cluster\"})",
     "legendFormat": "HTTP 3XX"
    },
    {
     "expr": "sum(code:apiserver_request_total:rate5m{code=~\"4..\", source_cluster=~\"$cluster\"})",
     "legendFormat": "HTTP 4XX"
    },
    {
     "expr": "sum(code:apiserver_request_total:rate5m{code=~\"5..\", source_cluster=~\"$cluster\"})",
     "legendFormat": "HTTP 5XX"
    }
   ]
  },
  {
   "title": "API Server Request Rate by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "code:apiserver_request_total:rate5m{source_cluster=~\"$cluster\"}",
     "legendFormat": "{{source_cluster}} : {{code}}"
    }
   ]
  },
  {
   "title": "Verb count by Cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (verb) (avg_over_time(resource_verb:apiserver_request_total:rate5m{source_cluster=~\"$cluster\"}[$__range]))",
     "legendFormat": " {{verb}}"
    }
   ]
  },
  {
   "title": "API Server - Request Rate by Resource and Verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "avg_over_time(resource_verb:apiserver_request_total:rate5m{source_cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{source_cluster}} {{resource}} {{verb}}"
    }
   ]
  },
  {
   "title": "Write / Read Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "write:apiserver_request_total:rate5m{source_cluster=~\"$cluster\"}",
     "legendFormat": "{{source_cluster}} : write"
    },
    {
     "expr": "read:apiserver_request_total:rate5m{source_cluster=~\"$cluster\"}",
     "legendFormat": "{{source_cluster}} : read"
    }
   ]
  },
  {
   "title": "Rate TLS handshake error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 49 },
   "targets": [
    {
     "expr": "cluster:apiserver_tls_handshake_errors_total:rate5m{source_cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}