{
 "title": "Prometheus Cardinality Analysis - 2",
 "tags": [
  "cardinality",
  "observability"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance_namespace",
    "query": {
     "query": "label_values(cardinality_exporter_series_count_by_metric_name_total,instance_namespace)"
    }
   },
   {
    "name": "source_cluster",
    "query": {
     "query": "label_values(cardinality_exporter_series_count_by_metric_name_total,source_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cardinality analysis dashboard",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard aggregates the tsdb status information from Konflux cluster prometheus instances. Note that User Workload Monitoring prometheus is not included, as it does not expose the tsdb status endpoint at this time (https://redhat.atlassian.net/browse/OBSDA-1356).  \n\nIt also shows the current status of our RHOBS active metric quota usage. Note that RHOBS has triple redundancy for sent metrics, so 100 forwarded series will show up as 300 active series.\n\nThe prometheus instances are deployed in various namespaces, so we use instance_namespace to select the specific deployments.\n\n\n"
   }
  },
  {
   "title": "tsdb head series of selected instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{source_cluster=\"$source_cluster\",namespace=\"$instance_namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RHOBS stage series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{tenant=\"0031e8d6-e50a-47ea-aecb-c7e0bd84b3f1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total cardinality of highest cardinality metrics in TSDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (instance_namespace,source_cluster,sharded_instance)(cardinality_exporter_series_count_by_metric_name_total{instance_namespace=\"$instance_namespace\",source_cluster=\"$source_cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RHOBS production series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{tenant=\"0031e8d6-e50a-47ea-aecb-c7e0bd84b3f1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Series Count by Metric Name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Top 10 Metrics by Series Count",
   "type": "timeseries",
   "description": "Overview of 10 highest cardinality metric series.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, max by (metric) (cardinality_exporter_series_count_by_metric_name_total{instance_namespace=\"${instance_namespace}\",source_cluster=\"$source_cluster\"}))",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Series Count by Label-Value Pair",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "Top 20 Label-Value Pairs by Series Count",
   "type": "timeseries",
   "description": "Shows how many series have a specific label-value pair.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "topk(20, max by (label_pair) (cardinality_exporter_series_count_by_label_value_pair_total{instance_namespace=\"$instance_namespace\"}))",
     "legendFormat": "{{label_pair}}"
    }
   ]
  },
  { "title": "Label Cardinality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Unique Values per Label Name",
   "type": "timeseries",
   "description": "High number of unique label values can contribute significantly to high cardinality.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "topk(20, max by (label) (cardinality_exporter_label_value_count_by_label_name_total))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Memory Usage by Label Name",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, max by (label) (cardinality_exporter_memory_by_label_name_bytes))",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}