{
 "title": "Kanary Signal Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "kanary_datasource", "label": "kanary datasource", "query": "prometheus" },
   {
    "name": "kanary_clusters",
    "label": "Kanary Clusters",
    "query": {
     "query": "label_values(kanary_up,tested_cluster)"
    }
   },
   { "name": "kanary_type", "label": "Kanary Type", "query": { "query": "label_values(kanary_up,type)" } }
  ]
 },
 "panels": [
  { "title": "Kanary Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kanary Up Signal",
   "type": "stat",
   "description": "Overview of the kanary signal status per cluster",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (tested_cluster) (kanary_up{tested_cluster=~\"${kanary_clusters}\", type=~\"${kanary_type}\", namespace=\"konflux-otel\"})",
     "legendFormat": "{{tested_cluster}}"
    }
   ]
  },
  {
   "title": "Kanary Error Signal",
   "type": "stat",
   "description": "Overview of the kanary error signal which indicates an issue in the kanary signal processing for a given cluster.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (tested_cluster) (kanary_error{tested_cluster=~\"${kanary_clusters}\", type=~\"${kanary_type}\", namespace=\"konflux-otel\"})",
     "legendFormat": "{{tested_cluster}}"
    }
   ]
  },
  {
   "title": "Kanary last push time",
   "type": "stat",
   "description": "Minutes since last push of the kanary result",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (tested_cluster, type) (\n  (\n    time() - kanary_last_push_timestamp{tested_cluster=~\"${kanary_clusters}\", type=~\"${kanary_type}\", namespace=\"konflux-otel\"}\n  ) / 60\n)",
     "legendFormat": "{{tested_cluster}}"
    }
   ]
  },
  { "title": "Kanary Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Cluster Availability Overview",
   "type": "gauge",
   "description": "Shows the availability of the cluster within the selected time range.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (tested_cluster) (avg_over_time(kanary_up{tested_cluster=~\"${kanary_clusters}\", type=~\"${kanary_type}\", namespace=\"konflux-otel\"}[$__range]))",
     "legendFormat": "{{tested_cluster}}"
    }
   ]
  },
  {
   "title": "Kanary Error Frequency",
   "type": "gauge",
   "description": "Shows the frequency of a kanary error signal reason for a given time range.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (tested_cluster, reason) (avg_over_time(kanary_error{tested_cluster=~\"${kanary_clusters}\", type=~\"${kanary_type}\", namespace=\"konflux-otel\"}[$__range]))",
     "legendFormat": "{{tested_cluster}}->{{reason}}"
    }
   ]
  },
  {
   "title": "Kanary Error Signal",
   "type": "table",
   "description": "Kanary signal processing error overview.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (tested_cluster, reason) (kanary_error{tested_cluster=~\"${kanary_clusters}\", type=~\"${kanary_type}\", namespace=\"konflux-otel\"})",
     "legendFormat": "{{tested_cluster}}"
    }
   ]
  },
  { "title": "Kanary Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Kanary Critical Alerts",
   "type": "alertlist",
   "description": "This will show the kanary signal critical alerts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 }
  },
  {
   "title": "Kanary Warning Alerts",
   "type": "alertlist",
   "description": "This will show the kanary signal warning alerts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 }
  }
 ]
}