{
 "title": "Release Service breakdown",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(source_cluster)" } },
   {
    "name": "tenant",
    "label": "managed tenant",
    "query": {
     "query": "label_values(release_total,target)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Release Service breakdown" } },
  { "title": "release overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Release overview",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(release_total{release_reason!=\"\", source_cluster=~\"$cluster\"}[$__range])) by(release_reason)\n# sum(increase(release_total{target!=\"\"}[$__range])) by(target)",
     "legendFormat": "{{release_reason}}"
    },
    {
     "expr": "sum (label_replace( sum by (namespace) (increase(release_total{validation_reason=\"Failed\"}[$__range])  OR vector(0)), \"release_reason\", \"Invalid\", \"\",\"\")) by (release_reason)\n# sum (label_replace( sum by (namespace) (increase(release_total{validation_reason=\"Failed\"}[$__range])  OR vector(0)), \"target\", \"Invalid\", \"\",\"\")) by (target)",
     "legendFormat": "{{release_reason}}"
    },
    {
     "expr": "label_replace( sum by (namespace) (release_concurrent_total), \"release_reason\", \"Concurrent\", \"\", \"\") ",
     "legendFormat": "{{release_reason}}"
    },
    {
     "expr": "label_replace( (sum by (namespace) (release_total{release_reason=\"Succeeded\", target=~\"$tenant\"}) / sum by (namespace) (release_total)) , \"release_reason\", \"Succeeded %\", \"\",\"\")\n# label_replace( (sum by (namespace) (release_total{target=\"Succeeded\", target=~\"$tenant\"}) / sum by (namespace) (release_total)) , \"target\", \"Succeeded %\", \"\",\"\")",
     "legendFormat": "{{release_reason}}"
    },
    {
     "expr": "label_replace( (sum by (namespace) (release_total{release_reason=\"Failed\", target=~\"$tenant|\"}) / sum by (namespace) (release_total)) , \"release_reason\", \"Failed %\", \"\",\"\")",
     "legendFormat": "{{release_reason}}"
    },
    {
     "expr": "avg(sum(rate(release_total{release_reason=\"Failed\"}[60m])) by(job) / sum(rate(release_total[60m])) by (job))\n# avg(sum(rate(release_total{target=\"Failed\"}[60m])) by(job) / sum(rate(release_total[60m])) by (job))",
     "legendFormat": "Failure rate (60m)"
    },
    {
     "expr": "  avg_over_time\n  (\n    (\n      count(sum(kube_pod_container_status_ready{namespace=\"release-service\", container=\"manager\", source_cluster=~\"$cluster\"})\n          by(namespace, source_cluster) > 0)\n        by(namespace)\n    ) [1d:]\n  )\n  /\n  count(max_over_time(sum(kube_pod_container_status_ready{namespace=\"release-service\", container=\"manager\", source_cluster=~\"$cluster\"}) by(source_cluster, namespace)[1d:])) by(namespace)",
     "legendFormat": "Pod availability"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 }, "options": { "content": "#### release duration\n---" } },
  {
   "title": "time to succeed",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, release_reason, le) (increase(release_duration_seconds_bucket{release_reason=\"Succeeded\", source_cluster=~\"$cluster\"}[$__range]))\n#sum by (namespace, target, le) (release_duration_seconds_bucket{target=\"Succeeded\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "release duration state timeline",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(namespace, le) (increase(release_duration_seconds_bucket{source_cluster=~\"$cluster\"}[$__range])) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "time to fail",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, release_reason, le) (increase(release_duration_seconds_bucket{release_reason=\"Failed\", source_cluster=~\"$cluster\"}[$__range]))\n# sum by(namespace, target, le) (release_duration_seconds_bucket{target=\"Failed\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 }, "options": { "content": "---\n#### service breakdown" } },
  {
   "title": "releases processing count over time",
   "type": "timeseries",
   "description": "Show the accumulated amount of releases over time. These numbers are reset when the controller is restarted",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (release_reason) (release_total{release_reason=~\"Failed|Succeeded\", source_cluster=~\"$cluster\"})\n# sum by (target) (release_total{target=~\"Failed|Succeeded\"})# ",
     "legendFormat": "{{release_reason}}"
    }
   ]
  },
  {
   "title": "releases 95% duration quantile over time",
   "type": "timeseries",
   "description": "The release duration quantile, show the 0.95 quantile of a release duration.\n\nhttps://en.wikipedia.org/wiki/Quantile",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (release_reason, le) (rate(release_duration_seconds_bucket{release_reason=~\"Failed|Succeeded\", source_cluster=~\"$cluster\"}[$__rate_interval])))\n# histogram_quantile(0.5, sum by (target, le) (rate(release_duration_seconds_bucket{target=~\"Failed|Succeeded\"}[$__rate_interval])))",
     "legendFormat": "Average_{{target}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (release_reason, le) (rate(release_duration_seconds_bucket{release_reason=~\"Failed|Succeeded\"}[$__rate_interval])))\n# histogram_quantile(0.95, sum by (target, le) (rate(release_duration_seconds_bucket{target=~\"Failed|Succeeded\"}[$__rate_interval])))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "slowest releases (99% quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (target, le) (rate(release_duration_seconds_bucket{release_reason=~\"Failed|Succeeded\",source_cluster=~\"$cluster\"}[$__rate_interval])) > 0)\n# histogram_quantile(0.99, sum by (release_reason, le) (rate(release_duration_seconds_bucket{target=~\"Failed|Succeeded\"}[$__rate_interval])) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "releases failures",
   "type": "timeseries",
   "description": "Show the accumulated amount of releases over time. These numbers are reset when the controller is restarted",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n    (sum (release_total{release_reason=~\"Failed\",source_cluster=~\"$cluster\"}) by (namespace) ) / ( sum(release_total) by (namespace) ),\n\"label\", \"Failed\",  \"\", \"\")\n\n#label_replace(\n#    (sum (release_total{target=~\"Failed\"}) by (namespace) ) / ( sum(release_total) by (namespace) ),\n#\"label\", \"Failed\",  \"\", \"\")",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "releases failure rate",
   "type": "timeseries",
   "description": "Show the release failure rate over time.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(release_total{release_reason=\"Failed\", source_cluster=~\"$cluster\"}[60m])) by(job) / sum(rate(release_total[60m])) by (job))\n# (sum(rate(release_total{target=\"Failed\"}[60m])) by(job) / sum(rate(release_total[60m])) by (job))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "release start progressing",
   "type": "timeseries",
   "description": "The time it takes for a release to get into Progressing state. It probably starts below 1 second, by currently our minimum sample it 5 seconds.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum(rate(release_pre_processing_duration_seconds_bucket{source_cluster=~\"$cluster\"}[$__rate_interval])) by(le, job)))",
     "legendFormat": "progressing"
    }
   ]
  },
  {
   "title": "Internal services overview (Different data source, not using RHTAP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "succeeded pipelineruns duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds{namespace=\"stonesoup-int-srvc\", status=\"success\"}) by(pipeline)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "succeeded taskruns duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds{namespace=\"stonesoup-int-srvc\", status=\"success\" }) by (task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 }, "options": { "content": "---\n---" } },
  {
   "title": "Signature Requests/Upload Pod status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"stonesoup-int-srvc\", pod=~\".*request-and-upload.*\"})by(phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pods in the namespace",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"stonesoup-int-srvc\", container!=\"manager\"})",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"stonesoup-int-srvc\", condition=\"true\"} > 0)",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"stonesoup-int-srvc\", container!=\"manager\"}) +\nsum(kube_pod_status_ready{namespace=\"stonesoup-int-srvc\", condition=\"true\"} > 0)",
     "legendFormat": "all pods"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
   "options": {
    "content": "---\n##### internal services controller\n---"
   }
  },
  {
   "title": "manager container status change timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{container=\"manager\", namespace=\"stonesoup-int-srvc\"} > 0) by (reason)\nOR\nsum(kube_pod_container_status_waiting_reason{container=\"manager\", namespace=\"stonesoup-int-srvc\"} > 0) by (reason)\nOR\n(sum(kube_pod_container_status_last_terminated_reason{container=\"manager\", namespace=\"stonesoup-int-srvc\"} > 0) by (reason) ) != (sum(kube_pod_container_status_ready{namespace=\"stonesoup-int-srvc\", container=\"manager\"} > 0))\nOR\nlabel_replace(sum(sum(kube_pod_container_status_ready{namespace=\"stonesoup-int-srvc\", container=\"manager\"} > 0) by(container)) without(container), \"reason\", \"Ready\", \"\", \"\")\nOR\ncount(label_replace(timestamp(increase(kube_pod_container_status_restarts_total{namespace=\"stonesoup-int-srvc\", container=\"manager\"}[2m]) > 0), \"reason\",  \"Restart\", \"\", \"\")) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "manager restarts (internal-services)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 59 },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=\"stonesoup-int-srvc\", container=\"manager\"}[$interval])) by(container, pod)",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "internal services controller availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time\n(\n  (\n    sum(kube_pod_container_status_ready{namespace=\"stonesoup-int-srvc\", container=\"manager\"} <= 3 ) by(namespace) > 0\n   ) [1d:]\n)\n/ sum(max_over_time(sum(kube_pod_container_status_ready{namespace=\"stonesoup-int-srvc\", container=\"manager\"}) by(namespace)[1d:])) by(namespace)",
     "legendFormat": "pod availability"
    }
   ]
  },
  { "title": "Release operator overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 68 }, "options": { "content": "---\n##### container info\n---" } },
  {
   "title": "manager memory usage ($cluster)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"release-service\", container=\"manager\",source_cluster=~\"$cluster\"}) by(container)",
     "legendFormat": "used"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"release-service\", container=\"manager\", resource=\"memory\", source_cluster=~\"$cluster\"}) by(container)",
     "legendFormat": "limits"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"release-service\", container=\"manager\", resource=\"memory\", source_cluster=~\"$cluster\"}) by(container)",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "manager cpu usage ($cluster)",
   "type": "timeseries",
   "description": "Graph in logarithmic style to improve viewing.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"release-service\", container=\"manager\", source_cluster=~\"$cluster\"}[$__interval])) by (container)  ",
     "legendFormat": "used"
    },
    {
     "expr": "(max(kube_pod_container_resource_limits{namespace=\"release-service\", container=\"manager\", resource=\"cpu\", source_cluster=~\"$cluster\"}) by(container))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"release-service\", container=\"manager\", resource=\"cpu\", source_cluster=~\"$cluster\"}) by(container)",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 85 },
   "options": {
    "content": "---\n##### release controller\n---"
   }
  },
  {
   "title": "release controller manager status timeline",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "label_replace(sum(sum(kube_pod_container_status_ready{namespace=\"release-service\", container=\"manager\", source_cluster=~\"$cluster\"} > 0) by(container, source_cluster)) without(container), \"reason\", \"Ready\", \"\", \"\")\nOR\nsum(kube_pod_container_status_waiting_reason{container=\"manager\", namespace=\"release-service\", source_cluster=~\"$cluster\"} > 0) by (reason, source_cluster)\nOR\nsum(kube_pod_container_status_terminated_reason{container=\"manager\", namespace=\"release-service\", source_cluster=~\"$cluster\"} > 0) by (reason, source_cluster)\nOR\ncount(label_replace(timestamp(increase(kube_pod_container_status_restarts_total{namespace=\"release-service\", container=\"manager\", source_cluster=~\"$cluster\"}[10m]) > 0), \"reason\",  \"Restart\", \"\", \"\")) by (reason,source_cluster)\n",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "release controller availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  avg_over_time\n  (\n    (\n      count(sum(kube_pod_container_status_ready{namespace=\"release-service\", container=\"manager\", source_cluster=~\"$cluster\"})\n          by(namespace, source_cluster) > 0)\n        by(namespace)\n    ) [1h:]\n  )\n  /\n  count(max_over_time(sum(kube_pod_container_status_ready{namespace=\"release-service\", container=\"manager\", source_cluster=~\"$cluster\"}) by(source_cluster, namespace)[1h:])) by(namespace)",
     "legendFormat": "pod availability"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 95 },
   "options": {
    "content": "---\n##### internal metrics\n---"
   }
  },
  {
   "title": "Total number of reconciles by type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum by (result) (controller_runtime_reconcile_total{controller=\"release\", namespace=\"release-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue retries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "label_replace(sum(workqueue_retries_total{name=\"release\"}),\"label\", \"absolute\", \"\", \"\")",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "label_replace(sum(increase(workqueue_retries_total{name=\"release\"}[$__rate_interval])), \"label\", \"increase rate\", \"\", \"\")",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}