{
 "title": "MintMaker dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source_cluster", "label": "source cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Useful links",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "- Namespace dashboard: https://grafana.app-sre.devshift.net/d/eetkzyh60ix34e/konflux-namespace-activity Cluster links: "
   }
  },
  { "title": "MintMaker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Time since last trigger",
   "type": "stat",
   "description": "Time elapsed since last DUC creation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - max by(source_cluster) (mintmaker_dependency_update_check_creation_time{source_cluster=~\"$source_cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipelineruns failure rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(pod) (mintmaker_pipelinerun_scheduled{source_cluster=~\"$source_cluster\", status=\"failure\"}) /ignoring(status) sum without(pod) (mintmaker_pipelinerun_scheduled{source_cluster=~\"$source_cluster\", status=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Cluster RAM requested (%)",
   "type": "timeseries",
   "description": "Percentage of the total RAM requested in each cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(source_cluster) (namespace_memory:kube_pod_container_resource_requests:sum{source_cluster=~\"$source_cluster\"}) / on(source_cluster) sum by(source_cluster) (kube_node_status_allocatable{resource=\"memory\", source_cluster=~\"$source_cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory-pressured nodes (%)",
   "type": "timeseries",
   "description": "Percentage of nodes in memory-pressured state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(source_cluster) (kube_node_status_condition{source_cluster=~\"$source_cluster\"}) / count by(source_cluster)(kube_node_role{source_cluster=~\"$source_cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}