{
 "title": "registry monitoring dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   {
    "name": "source_cluster",
    "query": {
     "query": "label_values(registry_exporter_success,source_cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(registry_exporter_success{source_cluster=~\"$source_cluster\"},node)"
    }
   },
   {
    "name": "test_type",
    "query": {
     "query": "label_values(registry_exporter_success,type)"
    }
   },
   {
    "name": "image_registry",
    "query": {
     "query": "label_values(registry_exporter_success,tested_registry)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quay.io Blackbox health check",
   "type": "stat",
   "description": "Shows overall status across all nodes and registry tests",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://quay.io/health\",source_cluster=~\"${source_cluster}\"}",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "Cluster Overview",
   "type": "stat",
   "description": "Shows overall status across all nodes and registry tests",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "konflux_up{check=\"${image_registry}\",source_cluster=~\"${source_cluster}\"}",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "Rate of cluster pull failures per minute",
   "type": "timeseries",
   "description": "Total rate of pull failures reported by cluster nodes\n\nThis serves as additional signal that can be used to confirm a cluster-wide outage.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate(container_runtime_crio_image_pulls_failure_total{source_cluster=~\"${source_cluster}\"}[1m])) by (source_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall ${test_type} status",
   "type": "stat",
   "description": "OK if test is passing on all selected nodes of the cluster. Degraded if any node test failed.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "repeat": "test_type",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(registry_exporter_success{source_cluster=~\"${source_cluster}\",node=~\"${node}\",type=~\"${test_type}\"}) by (source_cluster)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Error reason tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors breakdown",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "repeat": "test_type",
     "targets": [
      {
       "expr": "registry_exporter_error{source_cluster=~\"${source_cluster}\",node=~\"${node}\",type=~\"${test_type}\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average rate of ${test_type} duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "repeat": "test_type",
     "targets": [
      {
       "expr": "  rate(registry_exporter_duration_seconds_sum{source_cluster=~\"${source_cluster}\",node=~\"${node}\",type=~\"${test_type}\"}[10m])\n/\n  rate(registry_exporter_duration_seconds_count{source_cluster=~\"${source_cluster}\",node=~\"${node}\",type=~\"${test_type}\"}[10m])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Minimal image size for ${test_type} check",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "repeat": "test_type",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(registry_exporter_image_size_mbytes{source_cluster=~\"${source_cluster}\", type=~\"${test_type}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Maximum image size for ${test_type} check",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "repeat": "test_type",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(registry_exporter_image_size_mbytes{source_cluster=~\"${source_cluster}\", type=~\"${test_type}\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}