{
 "title": "Konflux Cluster Upgrade Overview",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "org_id",
    "label": "OCM Organization",
    "query": {
     "query": "aus_cluster_upgrade_policy_info"
    }
   },
   {
    "name": "sectors",
    "label": "Sectors",
    "query": {
     "query": "label_values(aus_cluster_upgrade_policy_info{org_id=~\"$org_id\"},sector)"
    }
   },
   {
    "name": "workloads",
    "label": "Workloads",
    "query": {
     "query": "label_values(aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\"},workloads)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "clusters",
    "label": "Clusters",
    "query": {
     "query": "label_values(aus_cluster_upgrade_policy_info,cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Konflux Clusters Version Distribution on timeline $datasource",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"}",
     "legendFormat": "{{cluster_name}} - {{current_version}}"
    }
   ]
  },
  {
   "title": "Clusters upgrades 24h $datasource",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(sum by(cluster_uuid, current_version)(last_over_time({__name__=\"aus_cluster_upgrade_policy_info\"}[25h]))) by (__name__, cluster_uuid) * on (cluster_uuid) group_left (org_id, org_name, cluster_name, current_version) aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"} > 1) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters upgrades 24h $datasource",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "count(sum by(cluster_uuid, current_version)(last_over_time({__name__=\"aus_cluster_upgrade_policy_info\"}[25h]))) by (__name__, cluster_uuid) * on (cluster_uuid) group_left (org_id, org_name, cluster_name, current_version) aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"} * on (cluster_uuid) group_left(previous_version) label_replace(aus_cluster_upgrade_policy_info offset 25h, \"previous_version\", \"$1\", \"current_version\", \"(.+)\") > 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Konflux Clusters Version Distribution $datasource",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 4, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"}) by (current_version)",
     "legendFormat": "{{current_version}}"
    }
   ]
  },
  {
   "title": "Ongoing upgrades Konflux clusters $datasource",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "aus_cluster_upgrade_policy_info{org_name=\"RHTAP\", cluster_name=~\"$clusters\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ongoing upgrades $datasource",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((aus_cluster_version_remaining_soak_days{} <= -2 >= -3) * on (cluster_uuid) (aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ongoing upgrades $datasource",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "increase(timestamp(avg by (cluster_uuid, soaking_version) (aus_cluster_version_remaining_soak_days{} <= -2 >= -3))[25h:])\n* on (cluster_uuid, soaking_version) (aus_cluster_version_remaining_soak_days{} <= bool -2 >= -3)\n* on (cluster_uuid) group_left(cluster_name, org_name, current_version) aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters w/ failed upgrades 24h $datasource",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(\n    resets(\n    ((aus_cluster_version_remaining_soak_days == 0 or aus_cluster_version_remaining_soak_days == -2)*-1)[24h:]\n    )\n) by (cluster_uuid, soaking_version)\n* on (cluster_uuid, soaking_version) count(aus_cluster_version_remaining_soak_days) by (cluster_uuid, soaking_version)\n* on (cluster_uuid) group_left(cluster_name, ocm_env, org_name, current_version) aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed upgrades 24h $datasource",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 28 },
   "targets": [
    {
     "expr": "sum(\n    resets(\n    ((aus_cluster_version_remaining_soak_days == 0 or aus_cluster_version_remaining_soak_days == -2)*-1)[24h:]\n    )\n) by (cluster_uuid, soaking_version)\n* on (cluster_uuid, soaking_version) count(aus_cluster_version_remaining_soak_days) by (cluster_uuid, soaking_version)\n* on (cluster_uuid) group_left(cluster_name, ocm_env, org_name, current_version) aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}