{
 "title": "Konflux Backup",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  { "title": "Latest Backup Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup Success",
   "type": "table",
   "description": "Number of successful backups in the last 24h.",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_success_total{source_cluster=~\"$cluster\"}[24h])) by (source_cluster)",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "Backup Failures",
   "type": "table",
   "description": "Number of backup failures in the last 24h.",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_failure_total{source_cluster=~\"$cluster\"}[24h])) by (source_cluster)",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "Backup Partial Failures",
   "type": "table",
   "description": "Number of backup partial failures in the last 24h.",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_partial_failure_total{source_cluster=~\"$cluster\"}[24h])) by (source_cluster)",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "Backup Age",
   "type": "table",
   "description": "Time since the last successful backup for a specific schedule.",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - avg(velero_backup_last_successful_timestamp{schedule=\"backup-tenants\",source_cluster=~\"$cluster\"}) by (source_cluster)",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  { "title": "Backup Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Backup Failures",
   "type": "timeseries",
   "description": "Number of backup failure increase based on selected interval.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_failure_total{source_cluster=~\"$cluster\"}[$__range])) by (source_cluster)",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "Total Backup Partial Failures",
   "type": "timeseries",
   "description": "Number of backup partial failures increase based on selected interval.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_partial_failure_total{source_cluster=~\"$cluster\"}[$__range])) by (source_cluster)",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  }
 ]
}