{
 "title": "Konflux ArgoCD",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "project",
    "query": {
     "query": "label_values(argocd_app_health_status, project)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=120&v=4)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "ArgoCD Controller Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"argocd-metrics\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "ArgoCD ApplicationSet Controller Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=~\"argocd-applicationset-controller|argocd-metrics|argocd-server-metrics\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "ArgoCD Server Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"argocd-server-metrics\",namespace=~\"$namespace\",project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Total Applications",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{health_status=\"Healthy\",namespace=~\"$namespace\"} == 1)"
    }
   ]
  },
  {
   "title": "Degraded",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{health_status=\"Degraded\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Health Percentage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{health_status=\"Healthy\",namespace=~\"$namespace\"}) * 100 / sum(argocd_app_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Synced",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Synced\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "OutOfSync",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"OutOfSync\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Sync Success Percentage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Synced\",namespace=~\"$namespace\"}) * 100 / sum(argocd_app_info{namespace=~\"$namespace\"})"
    }
   ]
  }
 ]
}