{
 "title": "Konflux Alerts",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Select Cluster", "query": { "query": "label_values(source_cluster)" } },
   { "name": "alertname", "label": "AlertName", "query": { "query": "label_values(ALERTS,alertname)" } },
   { "name": "severity", "label": "Severity", "query": { "query": "label_values(ALERTS,severity)" } },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "query_result(max_over_time(ALERTS{}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alert Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max Alert Count",
   "type": "piechart",
   "description": "Maximum Alert Count by alert name for a selected time range. ",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(alerts_for_state_firing{severity=~\"$severity\",alertname=~\"$alertname\",source_cluster=~\"$cluster\"}[$__range]) + 1 ) by (alertname,severity)",
     "legendFormat": "{{alertname}}"
    },
    {
     "expr": "sum(changes(alerts_for_state_firing{severity=~\"$severity\",check=~\"probe-multicluster\",alertname=~\"$alertname\"}[$__range]) + 1 ) by (job,alertname,severity)",
     "legendFormat": "{{alertname}} {{job}}"
    }
   ]
  },
  {
   "title": "Alert Count by Cluster and Dependency",
   "type": "barchart",
   "description": "Max number of  alerts by cluster or dependency",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum(changes(alerts_for_state_firing{severity=~\"$severity\",check=~\"probe-multicluster\",alertname=~\"$alertname\"}[$__range]) + 1) by(job) or sum(changes(alerts_for_state_firing{severity=~\"$severity\",alertname=~\"$alertname\",source_cluster=~\"$cluster\"}[$__range]) + 1) by(source_cluster)",
     "legendFormat": "{{source_cluster}} {{job}}"
    },
    { "legendFormat": "{{source_cluster}} " }
   ]
  },
  {
   "title": "Alert Count by Severity",
   "type": "bargauge",
   "description": "Alert Count by severity  for a selected time range. ",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(alerts_for_state_firing{severity=~\"$severity\",alertname=~\"$alertname\",source_cluster=~\"$cluster\"}[$__range]) + 1 ) by (severity)",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum(changes(alerts_for_state_firing{severity=~\"$severity\",check=~\"probe-multicluster\",alertname=~\"$alertname\"}[$__range]) + 1 ) by (alertname,severity)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Alert Volume",
   "type": "state-timeline",
   "description": "Alert volume by alert name by selected cluster, excluded multicluster probes.",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum by (severity) (\n  changes(\n    alerts_for_state_firing{\n      severity=~\"$severity\",\n      alertname=~\"$alertname\",\n      source_cluster=~\"$cluster\"\n    }[$__range]\n  ) + 1\n) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert Heatmap per Component",
   "type": "heatmap",
   "description": "Heatmap of alert count by alert name filterable by affected component",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(changes(alerts_for_state_firing{severity=~\"$severity\",alertname=~\"$alertname\",source_cluster=~\"$cluster\", component=~\"$component\"}[$__range]) + 1) by(alertname, source_cluster, tested_cluster)",
     "legendFormat": "{{alertname}} {{source_cluster}} {{tested_cluster}}"
    }
   ]
  }
 ]
}