{
 "title": "Konflux SLOs",
 "description": "Konflux Service Level Objectives",
 "time": { "from": "now-28d", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Integration Service SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency Service Response SLO",
   "type": "text",
   "description": "The objective for the given time window.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "options": {
    "content": "<h1><center>90% of requests must be within required response time</center></h1>"
   }
  },
  {
   "title": "Measured",
   "type": "gauge",
   "description": "The current measurement for the given time window.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(integration_svc_response_seconds_bucket{le=\"30.0\"}[$__rate_interval])) by (job)\n/\nsum(rate(integration_svc_response_seconds_count[$__rate_interval]) > 0) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to start Pipeline Run",
   "type": "text",
   "description": "The objective for the given time window.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "options": {
    "content": "<h1><center>90% of requests must be within required time</center></h1>"
   }
  },
  {
   "title": "Measured",
   "type": "gauge",
   "description": "The current measurement for the given time window.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(integration_svc_snapshot_created_to_pipelinerun_started_seconds_bucket{le=\"5.0\"}[$__rate_interval])) by (job)\n/\nsum(rate(integration_svc_snapshot_created_to_pipelinerun_started_seconds_count[$__rate_interval]) > 0) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency of Release Creation",
   "type": "text",
   "description": "The objective for the given time window.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "options": {
    "content": "<h1><center>90% of requests must be within required time</center></h1>"
   }
  },
  {
   "title": "Measured",
   "type": "gauge",
   "description": "The current measurement for the given time window.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(integration_svc_release_latency_seconds_bucket{le=\"10.0\"}[$__rate_interval])) by (job) / sum(rate(integration_svc_release_latency_seconds_count[$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Release Service SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Release Validation SLO",
   "type": "text",
   "description": "Measure the time it takes for a Release to be marked as Validated.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 23 },
   "options": {
    "content": "<h1><center>90% of the Releases should be validated below 5 seconds</center></h1>"
   }
  },
  {
   "title": "Measured",
   "type": "gauge",
   "description": "Measure the time it takes for a Release to be marked as Processed.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(release_validation_duration_seconds_bucket{le=\"5.0\"}[$__rate_interval])) / sum by (job) (rate(release_validation_duration_seconds_count[$__rate_interval]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Release Pre-Processing SLO",
   "type": "text",
   "description": "Measure the time it takes for a Release to be marked as Processing",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 30 },
   "options": {
    "content": "<h1><center>90% of the Releases should be pre-processed within 10 seconds</center></h1>"
   }
  },
  {
   "title": "Measured",
   "type": "gauge",
   "description": "Measure the time it takes for a Release to be marked as Processed.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(release_pre_processing_duration_seconds_bucket{le=\"10.0\"}[$__rate_interval])) / sum by (job) (rate(release_pre_processing_duration_seconds_count[$__rate_interval]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pipeline SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Pipeline Controller Restarts",
   "type": "text",
   "description": "The rate that any of the pipeline controllers have restarted",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 38 },
   "options": {
    "content": "<h1><center>The rate that any of the pipeline controllers have restarted</center></h1>"
   }
  },
  {
   "title": "Controller Restart Rates",
   "type": "stat",
   "description": "The number of times any of the tekton controllers have restarted",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\", pod=~\"tekton-.*|pipelines-as-code-.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocked PipelineRuns",
   "type": "text",
   "description": "The number of validated PipelineRuns not yet processed by the PipelineRun Controller.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 45 },
   "options": {
    "content": "<h1><center>The number of validated PipelineRuns not yet processed by the PipelineRun Controller.</center></h1>"
   }
  },
  {
   "title": "Deadlocked PipelineRuns",
   "type": "stat",
   "description": "The number of validated PipelineRuns not yet processed by the PipelineRun Controller.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pipelinerun_kickoff_not_attempted_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocked TaskRuns",
   "type": "text",
   "description": "The rate of validated TaskRuns not yet processed by the TaskRuns Controller.  Negative numbers mean no TaskRuns Controller deadlocks despite Kubernetes throttling.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 52 },
   "options": {
    "content": "<h1><center>The rate of validated TaskRuns not yet processed by the TaskRuns Controller.  Negative numbers mean no TaskRun Controller deadlocks despite Kubernetes throttling.</center></h1>"
   }
  },
  {
   "title": "Deadlocked TaskRuns",
   "type": "stat",
   "description": "The rate of validated TaskRuns not yet processed by the TaskRuns Controller.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(taskrun_pod_create_not_attempted_or_pending_count[$__range])) - sum(rate(tekton_pipelines_controller_running_taskruns_throttled_by_quota[$__range])) - sum(rate(tekton_pipelines_controller_running_taskruns_throttled_by_node[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocked ResolutionRequests",
   "type": "text",
   "description": "The number of validated ResolutionRequests  not yet processed by the Resolver Controller.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 59 },
   "options": {
    "content": "<h1><center>The number of validated ResolutionRequests not yet processed by the Resolver Controller.</center></h1>"
   }
  },
  {
   "title": "Deadlocked ResolutionRequests",
   "type": "stat",
   "description": "The number of validated ResolutionRequests not yet processed by the Resolver Controller.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pending_resolutionrequest_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Results Deadlocked Part 1",
   "type": "text",
   "description": "Indicator whether Tekton Results is deadlocked",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 66 },
   "options": {
    "content": "<h1><center>If there are PipelineRuns on the cluster, but no corresponding GRPC processed by Tekton Results, Tekton Results is possibly deadlocked </center></h1>"
   }
  },
  {
   "title": "PipelineRun Total Rate - Results Deadlock Part 1",
   "type": "stat",
   "description": "The rate of PipelineRuns existing on cluster for the poling interval",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tekton_pipelines_controller_pipelinerun_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Results Deadlocked Part 2",
   "type": "text",
   "description": "Indicator whether Tekton Results is deadlocked",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 73 },
   "options": {
    "content": "<h1><center>If there are PipelineRuns on the cluster, but no corresponding GRPC processed by Tekton Results, Tekton Results is possibly deadlocked </center></h1>"
   }
  },
  {
   "title": "Tekton Results GRPC Rate - Results Deadlock Part 2",
   "type": "stat",
   "description": "The rate of PipelineRun related GRPC API calls made against Tekton Results",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job='tekton-results-api', grpc_service=~'tekton.results.*'}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Results Success Rate",
   "type": "text",
   "description": "Tekton Results API Success Rate",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 80 },
   "options": {
    "content": "<h1><center>Tekton Results API Success Rate </center></h1>"
   }
  },
  {
   "title": "Tekton Results API Success",
   "type": "gauge",
   "description": "The success rate of API calls made to Tekton Results",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job='tekton-results-api', grpc_service=~'tekton.results.*', grpc_code='OK'}[$__range])) / sum(rate(grpc_server_handled_total{job='tekton-results-api', grpc_service=~'tekton.results.*'}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocked Chains",
   "type": "text",
   "description": "The rate of PipelineRuns/TaskRuns still needing processing by Tekton Chains Controller",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 87 },
   "options": {
    "content": "<h1><center>The rate of PipelineRuns/TaskRuns still needing processing by Tekton Chains Controller</center></h1>"
   }
  },
  {
   "title": "Deadlocked Chains",
   "type": "stat",
   "description": "The rate of PipelineRuns/TaskRuns still needing processing by Tekton Chains Controller",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(watcher_workqueue_depth{container='tekton-chains-controller',app='tekton-chains-controller'}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocked PAC",
   "type": "text",
   "description": "The number of PipelineRuns/TaskRuns still needing processing by Tekton PAC Controller",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 94 },
   "options": {
    "content": "<h1><center>The number of PipelineRuns/TaskRuns still needing processing by Tekton PAC Controller</center></h1>"
   }
  },
  {
   "title": "Deadlocked PAC",
   "type": "stat",
   "description": "The number of PipelineRuns/TaskRuns still needing processing by Tekton PAC Controller",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pac_watcher_work_queue_depth[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Project Controller SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Availability SLO",
   "type": "text",
   "description": "The objective for the given time window.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 102 },
   "options": {
    "content": "<h1><center>100% of service replicas must be available within the measurment timeframe</center></h1>"
   }
  },
  {
   "title": "Measured",
   "type": "gauge",
   "description": "The current measurement for the given time window.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"project-controller\"})\n/\nsum(kube_deployment_spec_replicas{namespace=\"project-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Smee SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Server Availability SLO",
   "type": "text",
   "description": "The objective for the given time window.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 110 },
   "options": {
    "content": "<h1><center>100% of service replicas must be available within the measurment timeframe</center></h1>"
   }
  },
  {
   "title": "Measured",
   "type": "gauge",
   "description": "The current measurement for the given time window.",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"smee\"})\n/\nsum(kube_deployment_spec_replicas{namespace=\"smee\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Availability SLO",
   "type": "text",
   "description": "The objective for the given time window.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 118 },
   "options": {
    "content": "<h1><center>100% of service replicas must be available within the measurment timeframe</center></h1>"
   }
  },
  {
   "title": "Measured",
   "type": "gauge",
   "description": "The current measurement for the given time window.",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"smee-client\"})\n/\nsum(kube_deployment_spec_replicas{namespace=\"smee-client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "KubeArchive SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Availability SLO",
   "type": "text",
   "description": "The objective for the given time window.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 127 },
   "options": {
    "content": "<h1><center>100% of service replicas must be available within the measurment timeframe</center></h1>"
   }
  },
  {
   "title": "Measured",
   "type": "gauge",
   "description": "The current measurement for the given time window.",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(konflux_up{service=~\"kubearchive-.*\"}) / count(konflux_up{service=~\"kubearchive-.*\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "SLO Template", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "SLO",
   "type": "text",
   "description": "The objective for the given time window.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 135 },
   "options": {
    "content": "<h1><center>SLO Definition</center></h1>"
   }
  },
  {
   "title": "Measured",
   "type": "stat",
   "description": "The current measurement for the given time window.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error Budget (%)",
   "type": "stat",
   "description": "The remaining error budget for the given time window.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {}
   ]
  }
 ]
}