{
 "title": "Konflux Pipeline Service",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Tekton Scheduling Overhead",
     "type": "stat",
     "description": "The ratio of time needed for the Tekton controller to start processing a PipelineRun after its creation vs. the time needed to execute successful PipelineRuns",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(pipeline_service_schedule_overhead_percentage_sum{status='succeded', source_cluster=~\"$cluster\"}[2m])) / sum(increase(pipeline_service_schedule_overhead_percentage_count{status='succeded', source_cluster=~\"$cluster\"}[2m]))"
      }
     ]
    },
    {
     "title": "Tekton Execution Overhead",
     "type": "stat",
     "description": "Time gaps between TaskRuns relative to the overall duration of successful PipelineRuns",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(pipeline_service_execution_overhead_percentage_sum{status='succeded', source_cluster=~\"$cluster\"}[2m])) / sum(increase(pipeline_service_execution_overhead_percentage_count{status='succeded', source_cluster=~\"$cluster\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TaskRun Controller kickoff after Kubernetes scheduling checks pass",
     "type": "stat",
     "description": "Number of TaskRuns outside of Kubernetes Throttling where the Tekton Controller has yet to attempt to create its underlying Pod, or the TaskRun is still in Pending state for multiple scan iterations",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(taskrun_pod_create_not_attempted_or_pending_count{source_cluster=~\"$cluster\"}[2m])) - sum(increase(tekton_pipelines_controller_running_taskruns_throttled_by_quota{source_cluster=~\"$cluster\"}[2m])) - sum(increase(tekton_pipelines_controller_running_taskruns_throttled_by_node{source_cluster=~\"$cluster\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pipeline Controller Kickoff After Kubernetes scheduling checks pass",
     "type": "stat",
     "description": "Number of PipelineRuns outside of Kubernetes Throttling where the Tekton Controller has yet to attempt to process its correctly defined Task specifications for multiple scan iterations.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(pipelinerun_kickoff_not_attempted_count{source_cluster=~\"$cluster\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pipeline Controller Restarts",
     "type": "stat",
     "description": "The number of times any of the tekton controllers have restarted",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\", pod=~\"tekton-.*\", source_cluster=~\"$cluster\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Deadlocked ResolutionRequests",
     "type": "stat",
     "description": "The number of validated ResolutionRequests not yet processed by the Resolver Controller.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(pending_resolutionrequest_count{source_cluster=~\"$cluster\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline Failures & EaaS Anomalies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Failed Pipeline Runs by Tenant 1h Rate ($cluster)",
   "type": "timeseries",
   "description": "Displays the absolute volume of failed pipeline runs per tenant 1h Rate and source cluster over a 1-hour rolling window. Use this alongside the Failure Rate panel to verify if a high failure percentage is backed by a significant number of actual failures, filtering out low-volume noise.",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tekton_pipelines_controller_pipelinerun_total{status=\"failed\", source_cluster=~\"$cluster\"}[1h])) by (source_cluster, tenant_id)"
    }
   ]
  },
  {
   "title": "PipelineRun Failure Rate per hour ($cluster)",
   "type": "stat",
   "description": "PipelineRun Failure Rate per hour",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tekton_pipelines_controller_pipelinerun_total{status=\"failed\", source_cluster=~\"$cluster\"}[1h]))"
    }
   ]
  },
  {
   "title": "Failure Pipeline Rate (%) by Tenant 1h Rate ($cluster)",
   "type": "timeseries",
   "description": "Displays the percentage of failed pipeline runs out of total executions per tenant 1h Rate and source cluster over a 1-hour rolling window. This highlights widespread degradation regardless of a tenant's normal traffic volume. Note: Spikes to 100% can occur for tenants running only a single pipeline; always correlate with the absolute volume panel to confirm impact",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (source_cluster, tenant_id) (increase(tekton_pipelines_controller_pipelinerun_total{status=\"failed\", source_cluster=~\"$cluster\"}[1h]))\n  / on (source_cluster, tenant_id)\n  sum by (source_cluster, tenant_id) (increase(tekton_pipelines_controller_pipelinerun_total{source_cluster=~\"$cluster\"}[1h]))\n) * 100"
    }
   ]
  },
  {
   "title": "PipelineRun Failure Rate % per hour ($cluster)",
   "type": "stat",
   "description": "PipelineRun Failure Rate % per hour",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(tekton_pipelines_controller_pipelinerun_total{status=\"failed\", source_cluster=~\"$cluster\"}[1h]))\n  /\n  sum(rate(tekton_pipelines_controller_pipelinerun_total{source_cluster=~\"$cluster\"}[1h]))\n) "
    }
   ]
  },
  {
   "title": "PipelineRun and TaskRun Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "PipelineRuns Per Hour",
     "type": "timeseries",
     "description": "Completed PipelineRuns per hour",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 534 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(tekton_pipelines_controller_pipelinerun_total{source_cluster=~\"$cluster\"}[1h]))* 3600"
      }
     ]
    },
    {
     "title": "PipelineRun Success",
     "type": "stat",
     "description": "PipelineRun success per hour",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 534 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate(tekton_pipelines_controller_pipelinerun_total{status=\"success\", source_cluster=~\"$cluster\"}[1h])) / sum (rate(tekton_pipelines_controller_pipelinerun_total{source_cluster=~\"$cluster\"}[1h]))"
      }
     ]
    },
    {
     "title": "TaskRuns Per Hour",
     "type": "timeseries",
     "description": "Completed TaskRuns Per Hour",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 540 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(tekton_pipelines_controller_taskrun_total[1h]))* 3600"
      }
     ]
    },
    {
     "title": "TaskRun Success",
     "type": "stat",
     "description": "TaskRun success per hour",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 540 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate(tekton_pipelines_controller_taskrun_total{status=\"success\", source_cluster=~\"$cluster\"}[1h])) / sum (rate(tekton_pipelines_controller_taskrun_total{source_cluster=~\"$cluster\"}[1h]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipelines Controller Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Pipelineruns Running ",
     "type": "stat",
     "description": "Number of Pipelineruns executing currently",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 444 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (job) (tekton_pipelines_controller_running_pipelineruns{source_cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Taskruns Running ",
     "type": "stat",
     "description": "Number of Taskruns executing currently",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 444 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (service) (tekton_pipelines_controller_running_taskruns{source_cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Pipelines Controller Container Restarts - To check out if better graph or stats",
     "type": "timeseries",
     "description": "Frequency of Pipelines Controller restarts (This is experimental and may be removed in future)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 444 },
     "targets": [
      {
       "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\", pod=~\"tekton-pipelines-controller-.*\", source_cluster=~\"$cluster\"}[$__range])"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "timeseries",
     "description": "The workqueue for the Tekton Pipelines Reconcilers",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 452 },
     "targets": [
      {
       "expr": "avg(- workqueue_depth{namespace=\"openshift-pipelines\", service=\"pipeline-metrics-exporter-service\", container=\"pipeline-metrics-exporter\"})"
      }
     ]
    },
    {
     "title": "Taskruns Throttled by Node",
     "type": "timeseries",
     "description": "Number of taskruns executing currently whose underlying Pods or Containers are suspended by k8s because of Node level constraints",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 452 },
     "targets": [
      {
       "expr": "tekton_pipelines_controller_running_taskruns_throttled_by_node{source_cluster=~\"$cluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipelines Performance Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Taskruns Throttled by Quota",
     "type": "timeseries",
     "description": "Number of taskruns executing currently whose underlying Pods or Containers are suspended by k8s because of defined ResourceQuotas",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 485 },
     "targets": [
      {
       "expr": "tekton_pipelines_controller_running_taskruns_throttled_by_quota{source_cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Taskruns Throttled by Node",
     "type": "timeseries",
     "description": "Number of taskruns executing currently whose underlying Pods or Containers are suspended by k8s because of Node level constraints",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 485 },
     "targets": [
      {
       "expr": "tekton_pipelines_controller_running_taskruns_throttled_by_node{source_cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "PIpelineruns failed by PVC Quota",
     "type": "timeseries",
     "description": "Number of pipelineruns whose pods could not be started because of PVC quotas.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 493 },
     "targets": [
      {
       "expr": "pipelinerun_failed_by_pvc_quota_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipelines-as-code Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Watcher Client Results",
     "type": "timeseries",
     "description": "Total number of kubernetes api request for pipelines-as-code watcher",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 527 },
     "targets": [
      {
       "expr": "rate(pac_watcher_client_results[1h])*3600"
      }
     ]
    },
    {
     "title": "Watcher Workqueue Depth",
     "type": "timeseries",
     "description": "The workqueue depth for the Pipelines-as-code Reconcilers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 527 },
     "targets": [
      {
       "expr": "avg(pac_watcher_workqueue_unfinished_work_seconds_count)"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics Exporter Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Workqueue Depth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 610 },
     "targets": [
      {
       "expr": "workqueue_depth{namespace='openshift-pipelines',pod=~'pipeline-metrics-exporter.+', source_cluster=~\"$cluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tekton Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "API Success Rate",
     "type": "stat",
     "description": "Request success rate",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 618 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1 - sum(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code=~\"Internal|Unavailable|Unknown|Unimplemented|Canceled|Unauthenticated|ResourceExhausted|PermissionDenied|OutOfRange|InvalidArgument|FailedPrecondition|DeadlineExceeded|DataLoss|Aborted\", source_cluster=~\"$cluster\"}) / (sum(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", source_cluster=~\"$cluster\"}) - sum(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code=~\"NotFound\", source_cluster=~\"$cluster\"}))"
      }
     ]
    },
    {
     "title": "Watcher Work Queue Depth",
     "type": "stat",
     "description": "Watcher work queue depth",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 618 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(watcher_workqueue_depth{job=\"tekton-results-watcher\", source_cluster=~\"$cluster\"})",
       "legendFormat": "Queue Depth"
      }
     ]
    },
    {
     "title": "API Request Rate",
     "type": "stat",
     "description": "Requests/Second",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 618 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", source_cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "Request Rate"
      }
     ]
    },
    {
     "title": "API Request Latency",
     "type": "stat",
     "description": "Request latency 99%-tile",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 618 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", source_cluster=~\"$cluster\"}[10m])) by (le) )",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Watcher Reconcile Latency",
     "type": "stat",
     "description": "Reconcile latency 99%-tile - \nLatency of reconcile operations.",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 618 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(watcher_reconcile_latency_bucket{job=\"tekton-results-watcher\", source_cluster=~\"$cluster\"}[10m])) by (le) )",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "API Response Rate",
     "type": "timeseries",
     "description": "RPC execution rate",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 624 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", source_cluster=~\"$cluster\"}[10m])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "API Latency Distribution",
     "type": "heatmap",
     "description": "Latency Distribution",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 624 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handling_seconds_bucket{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", source_cluster=~\"$cluster\"}[10m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "API Server Errors",
     "type": "timeseries",
     "description": "Server error distribution across gRPC methods.             \nStatus Codes:\nInternal, Unavailable, Unknown, Unimplemented",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 633 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code!=\"OK\", source_cluster=~\"$cluster\"}[10m])) by (grpc_method)",
       "legendFormat": "RPC: {{grpc_method}}"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code=~\"Internal|Unavailable|Unknown|Unimplemented\", source_cluster=~\"$cluster\"}[10m])) by (grpc_code) / ignoring(grpc_code) group_left sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code!=\"OK\", source_cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "Error: {{grpc_code}}"
      }
     ]
    },
    {
     "title": "API Other Errors",
     "type": "timeseries",
     "description": "Other error distribution across gRPC methods.            \nStatus Codes Except:\nInternal, Unavailable, Unknown, Unimplemented",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 633 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code!=\"OK\", source_cluster=~\"$cluster\"}[10m])) by (grpc_method)",
       "legendFormat": "RPC: {{grpc_method}}"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code!~\"Internal|Unavailable|Unknown|Unimplemented\", source_cluster=~\"$cluster\"}[10m])) by (grpc_code) / ignoring(grpc_code) group_left sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code!=\"OK\", source_cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "Error: {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Watcher Reconcile Rate",
     "type": "timeseries",
     "description": "Number of reconcile operations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 641 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(watcher_reconcile_count{job=\"tekton-results-watcher\", source_cluster=~\"$cluster\"}[10m])) by (success)",
       "legendFormat": "{{success}}"
      }
     ]
    },
    {
     "title": "Watcher Latency",
     "type": "timeseries",
     "description": "Work queue latency at queue depth",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 641 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(watcher_workqueue_queue_latency_seconds_sum{job=\"tekton-results-watcher\", source_cluster=~\"$cluster\"}[10m]))/sum(rate(watcher_workqueue_queue_latency_seconds_count{job=\"tekton-results-watcher\", source_cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "Queue Latency"
      },
      {
       "expr": "sum(rate(watcher_reconcile_latency_sum{job=\"tekton-results-watcher\"}[10m]))/sum(rate(watcher_reconcile_latency_count{job=\"tekton-results-watcher\"}[10m]))/1000",
       "legendFormat": "Reconcile Latency"
      },
      {
       "expr": "sum(watcher_work_queue_depth{job=\"tekton-results-watcher\"})",
       "legendFormat": "Queue Depth"
      }
     ]
    }
   ]
  },
  {
   "title": "Tekton Chains",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Tekton Chains Work Queue Depth",
     "type": "stat",
     "description": "Tekton Chains work queue depth",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 675 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(watcher_workqueue_depth{container='tekton-chains-controller',app='tekton-chains-controller', source_cluster=~\"$cluster\"})",
       "legendFormat": "Queue Depth"
      }
     ]
    },
    {
     "title": "Tekton Chains Workqueue Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 675 },
     "targets": [
      {
       "expr": "rate(watcher_workqueue_longest_running_processor_seconds_count{app=\"tekton-chains-controller\", source_cluster=~\"$cluster\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tekton Chains Reconcile Latency",
     "type": "stat",
     "description": "Reconcile latency 99%-tile - \nLatency of reconcile operations.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 682 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(watcher_reconcile_latency_bucket{job=\"tekton-chains\"}[2m])) by (le) ) / 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tekton Chains CPU Fraction Use",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 682 },
     "targets": [
      {
       "expr": "rate(watcher_go_gc_cpu_fraction{app=\"tekton-chains-controller\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sprayproxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Requests - Check with Infra if spraypoxy panels are useful/needed.",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5013 },
     "targets": [
      {
       "expr": "rate(sprayproxy_http_inbound_requests_total{namespace=\"sprayproxy\", source_cluster=~\"$cluster\"}[5m]) * 300",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Forwarded Requests",
     "type": "timeseries",
     "description": "Forwarded attempts to backend server(s)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5013 },
     "targets": [
      {
       "expr": "rate(sprayproxy_http_forwarded_requests_total{source_cluster=~\"$cluster\"}[5m]) * 300",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response Time Duration",
     "type": "timeseries",
     "description": "Forwarded request duration in seconds",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5019 },
     "targets": [
      {
       "expr": "rate(sprayproxy_http_response_time_duration_seconds_bucket{source_cluster=~\"$cluster\"}[5m]) * 300",
       "legendFormat": "{{source_cluster}} : {{le}}"
      }
     ]
    }
   ]
  }
 ]
}