{
 "title": "Pulp Release Pipeline",
 "tags": [
  "pulp",
  "release-service",
  "tekton",
  "spre"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_container_status_terminated_reason{namespace=~\".*-tenant\"}, source_cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OOMKilled Pods",
   "type": "stat",
   "description": "OOMKilled containers in RPM release pipeline pods",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_status_terminated_reason{source_cluster=~\"$cluster\", reason=\"OOMKilled\", pod=~\".*(push-rpms-to-pulp|push-rpm-data-to-pyxis|upload-src-rpm-sbom-attestation).*\"}) or vector(0))",
     "legendFormat": "OOMKilled"
    }
   ]
  },
  { "title": "OOMKilled Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "OOMKilled Events Over Time",
   "type": "timeseries",
   "description": "OOMKilled events in RPM release pipeline pods over time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (source_cluster, namespace) (\n  kube_pod_container_status_terminated_reason{source_cluster=~\"$cluster\", reason=\"OOMKilled\", pod=~\".*(push-rpms-to-pulp|push-rpm-data-to-pyxis|upload-src-rpm-sbom-attestation).*\"}\n)",
     "legendFormat": "{{namespace}} ({{source_cluster}})"
    }
   ]
  },
  {
   "title": "OOMKilled RPM Release Pods",
   "type": "table",
   "description": "Details of OOMKilled RPM release pipeline pods",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (source_cluster, namespace, pod, container) (max_over_time(kube_pod_container_status_terminated_reason{source_cluster=~\"$cluster\", reason=\"OOMKilled\", pod=~\".*(push-rpms-to-pulp|push-rpm-data-to-pyxis|upload-src-rpm-sbom-attestation).*\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}