{
 "title": "Konflux Namespace Lister",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(konflux_up,service)"
    }
   },
   { "name": "cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  { "title": "Namespace lister availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace Lister availability - overall",
   "type": "gauge",
   "description": "The system's overall read replica availability percentage for the timeframe selected.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(count_over_time((konflux_up{service=~\"$service\", source_cluster=~\"$cluster\"} == 1)[$__range:]) / count_over_time(konflux_up{service=~\"$service\", source_cluster=~\"$cluster\"}[$__range:])) * 100",
     "legendFormat": "Global Average Uptime"
    }
   ]
  },
  {
   "title": "Namespace Lister replica availability per cluster",
   "type": "timeseries",
   "description": " replica availability per cluster for timeframe selected",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( (count_over_time(group by (service, source_cluster) (konflux_up{service=~\"$service\", source_cluster=~\"$cluster\"} == 1)[$__range:])) / (count_over_time(group by (service, source_cluster) (konflux_up{service=~\"$service\", source_cluster=~\"$cluster\"})[$__range:])) ) * 100",
     "legendFormat": "{{source_cluster}} - {{service}}"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Failures syncing cache per pod",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_lister_accesscache_synch_op_total{status=\"failed\"}) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed sync operations rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(namespace_lister_api_counter{code=~\"5..\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal errors rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(namespace_lister_api_counter{code=~\"5..|4..\"}[$__rate_interval])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal code count rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(namespace_lister_api_counter[$__rate_interval])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Namespace Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "sum(rate(namespace_lister_process_cpu_seconds_total{source_cluster=~\"$cluster\" , namespace=~\"$service\"}[5m])) by (source_cluster)",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "Memory usage ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(namespace_lister_process_resident_memory_bytes{source_cluster=~\"$cluster\" , namespace=~\"$service\"}) by (source_cluster)",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Average response time by return code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(code,source_cluster) (rate(namespace_lister_api_latency_sum{source_cluster=~\"$cluster\"}[5m])) / sum by(code,source_cluster) (rate(namespace_lister_api_latency_count{source_cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{source_cluster}}: {{code}}"
    }
   ]
  },
  {
   "title": "Network rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{source_cluster=~\"$cluster\",namespace=~\"$service\"}[5m])) by (source_cluster)",
     "legendFormat": "{{source_cluster}}: receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{source_cluster=~\"$cluster\",namespace=~\"$service\"}[5m])) by (source_cluster)",
     "legendFormat": "{{source_cluster}}: transmit"
    }
   ]
  },
  { "title": "Pods Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum without (verb) (namespace_lister_api_response_size_bucket{source_cluster=~\"$cluster\"} \n))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum without (verb) (namespace_lister_api_response_size_bucket{source_cluster=~\"$cluster\"} \n))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}