{
 "title": "Konflux Infra Probes",
 "description": "Blackbox Exporter Probes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(probe_success{job=~\"ibm-.*\"},source_cluster)"
    }
   },
   {
    "name": "probe",
    "label": "probe",
    "query": {
     "query": "label_values(probe_success{source_cluster=~\"$cluster\"},job)"
    }
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success{job=~\"$probe\", source_cluster=~\"$cluster\"},target)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Probe Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Probe Group Status",
   "type": "table",
   "description": "Last status by group of probes",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by (job,source_cluster) (probe_success{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\"}) / count by (job,source_cluster) (probe_success{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\"})",
     "legendFormat": "{{source_cluster}} {{job}}"
    }
   ]
  },
  {
   "title": "Probe Alerts",
   "type": "stat",
   "description": "Alert Status per probe group.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (check,source_cluster) (konflux_up{\ncheck!=\"probe\",\nsource_cluster=~\"$cluster\",job=~\"$probe\"}) \n/ count by (check,source_cluster) (konflux_up{\ncheck!=\"probe\",\nsource_cluster=~\"$cluster\",job=~\"$probe\"})",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "Probe Count",
   "type": "stat",
   "description": "Number of selected probes per cluster by probe group",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (job,source_cluster) (probe_success{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\"}) ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network Probe Status",
   "type": "state-timeline",
   "description": "VPN and PowerVS Probe Status",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_success{source_cluster=~\"$cluster\",job=~\".*-vpn|.*pwvs\"}",
     "legendFormat": "{{job}} {{target}}"
    }
   ]
  },
  {
   "title": "S390x Static Host  Status",
   "type": "state-timeline",
   "description": "Probe status to static hosts",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "probe_success{source_cluster=~\"$cluster\",target=~\"$target\",job=~\".*-static-host\",instance=~\"s390.*\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "PPC Static Host  Status",
   "type": "state-timeline",
   "description": "Probe status to static hosts",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "probe_success{source_cluster=~\"$cluster\",target=~\"$target\",job=~\".*-static-host\",instance=~\"ppc.*\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "Probe Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Highest Probe Duration",
   "type": "barchart",
   "description": "Top 5 highest probe duration in seconds",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, avg_over_time(probe_duration_seconds{source_cluster=~\"$cluster\",job=~\"$probe\",target=~\"$target\"}[10m])))",
     "legendFormat": " {{source_cluster}} {{target}}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "description": "Probe total duration in seconds",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\"}",
     "legendFormat": "{{target}} {{instance}}"
    }
   ]
  },
  {
   "title": "Probe ICMP RTT Duration",
   "type": "timeseries",
   "description": "ICMP Probe RTT phase Duration in seconds",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\",phase=\"rtt\"}",
     "legendFormat": "{{job}} {{target}}"
    }
   ]
  }
 ]
}