{
 "title": "Konflux Status Page",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster selection", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "&nbsp;\n# Konflux Status Page for **$cluster** cluster"
   }
  },
  {
   "title": "Provide a feedback!",
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 0 },
   "options": {
    "content": "Help us improve your experience - [feedback form](https://forms.gle/xZuYEac7s3Gk1xzcA)\n\nAny issues with the dashboard? Reach out in [#forum-konflux-o11y](https://redhat.enterprise.slack.com/archives/C04FDFTF8EB)!"
   }
  },
  { "title": "Signals overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Container Single Arch builds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kanary_error{tested_cluster=\"${cluster}\", type=\"container-single-arch\", namespace=\"konflux-otel\", phase!=\"upload-results-to-s3\"} == bool 1) + sum(kanary_up{tested_cluster=\"${cluster}\", type=\"container-single-arch\", namespace=\"konflux-otel\"} == bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Multi Arch builds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kanary_error{tested_cluster=\"${cluster}\", type=\"container-multi-arch\", namespace=\"konflux-otel\", phase!=\"upload-results-to-s3\"} == bool 1) + sum(kanary_up{tested_cluster=\"${cluster}\", type=\"container-multi-arch\", namespace=\"konflux-otel\"} == bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM builds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kanary_error{tested_cluster=\"${cluster}\", type=\"rpm\", namespace=\"konflux-otel\", phase!=\"upload-results-to-s3\"} == bool 1) + sum(kanary_up{tested_cluster=\"${cluster}\", type=\"rpm\", namespace=\"konflux-otel\"} == bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quay registry exporter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "konflux_up{check=\"quay.io\", source_cluster=\"${cluster}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe Group Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 4 },
   "targets": [
    {
     "expr": "sum by (job) (probe_success{source_cluster=~\"$cluster\"}) / count by (job) (probe_success{source_cluster=~\"$cluster\"})",
     "legendFormat": "{{job}} {{target}} {{source_cluster}}"
    }
   ]
  },
  { "title": "WebRCA Incidents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of currently active WebRCA incidents",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  incidents AS i\nJOIN\n  incident_products AS ip ON ip.incident_id = i.id\nWHERE\n i.status = 'ongoing' AND\n ip.product_id = 'ebfd6fef-1922-4bcb-a2f9-b33f586955ed';"
    }
   ]
  },
  {
   "title": "WebRCA incidents",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n i.incident_id,\n i.created_at,\n i.resolved_at,\n i.status,\n i.summary\nFROM\n incidents AS i\nJOIN\n incident_products AS ip ON ip.incident_id = i.id\nWHERE\n i.created_at <= $__timeTo() AND\n (\n   i.resolved_at >= $__timeFrom()\n   OR\n   (i.status = 'ongoing' AND i.resolved_at IS NULL)\n ) AND\n ip.product_id = 'ebfd6fef-1922-4bcb-a2f9-b33f586955ed'\nORDER BY\n i.created_at DESC;"
    }
   ]
  },
  { "title": "SLO Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Number of currently firing SLO Alerts ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{slo=\"true\", alertstate=\"firing\", source_cluster=\"$cluster\", tested_cluster=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Active SLO Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 } }
 ]
}