{
 "title": "MPC",
 "description": "Multi Platform Controller",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(source_cluster)" } },
   { "name": "platform", "label": "Platform", "query": { "query": "label_values(platform)" } }
  ]
 },
 "panels": [
  {
   "title": "Building blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Health & Availability ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Task status phase",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{namespace=\"multi-platform-controller\", source_cluster=~\"$cluster\"}) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of Unhealthy Deployments By Cluster",
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{namespace=\"multi-platform-controller\", source_cluster=~\"$cluster\"} != kube_deployment_status_replicas_ready{namespace=\"multi-platform-controller\", source_cluster=~\"$cluster\"})\nby (source_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Unavailable Platforms per Source Cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(multi_platform_controller_available{source_cluster=~\"$cluster\"} == 0) by (source_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Running OTP Pods Per Cluster",
   "type": "timeseries",
   "description": "The number of pods that are not in the \"Running\" phase for each cluster (should be 0).",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"multi-platform-controller\", pod=~\"multi-platform-otp.*\", source_cluster=~\"$cluster\"})\nby (source_cluster)\n-\nsum(kube_pod_status_phase{namespace=\"multi-platform-controller\", phase=\"Running\", pod=~\"multi-platform-otp.*\", source_cluster=~\"$cluster\"})\nby (source_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Running Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Current Running Tasks by Platform",
   "type": "gauge",
   "description": "The number of currently running tasks on each platform",
   "gridPos": { "h": 14, "w": 22, "x": 1, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(platform) (multi_platform_controller_running_tasks{source_cluster=~\"$cluster\", platform=~\"$platform\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Change in Running Tasks Per Platform (5m Window)",
   "type": "timeseries",
   "description": "Average per-second rate of increase or decrease in the number of running tasks over a 5-minute period.",
   "gridPos": { "h": 9, "w": 11, "x": 1, "y": 34 },
   "targets": [
    {
     "expr": "sum by(platform) (deriv(multi_platform_controller_running_tasks{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net Change in Running Tasks Per Platform (5m Window)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by(platform) (delta(multi_platform_controller_running_tasks{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Waiting Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Current waiting Tasks by Platform",
   "type": "gauge",
   "description": "he number of tasks waiting for an executor to be available to run",
   "gridPos": { "h": 14, "w": 22, "x": 1, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(platform) (multi_platform_controller_waiting_tasks{source_cluster=~\"$cluster\", platform=~\"$platform\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Change in Waiting Tasks Per Platform (5m Window)",
   "type": "timeseries",
   "description": "Average per-second rate of increase or decrease in the number of waiting tasks over a 5-minute period.",
   "gridPos": { "h": 9, "w": 11, "x": 1, "y": 58 },
   "targets": [
    {
     "expr": "sum by(platform) (deriv(multi_platform_controller_waiting_tasks{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net Change in Waiting Tasks Per Platform (5m Window)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum by(platform) (delta(multi_platform_controller_waiting_tasks{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Task Run Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Average Task Run Time Excluding Wait and Allocation Time (30m Window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by(platform) (\n  rate(multi_platform_controller_task_run_time_sum{source_cluster=~\"$cluster\", platform=~\"$platform\"}[30m])\n  -\n  rate(multi_platform_controller_wait_time_sum{source_cluster=~\"$cluster\", platform=~\"$platform\"}[30m])\n  -\n  rate(multi_platform_controller_host_allocation_time_sum{source_cluster=~\"$cluster\", platform=~\"$platform\"}[30m])\n)\n/\nsum by(platform) (\n  rate(multi_platform_controller_task_run_time_count{source_cluster=~\"$cluster\", platform=~\"$platform\"}[30m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile of Total Task Run Time (5m Window)",
   "type": "timeseries",
   "description": "Calculates the value that 95% of tasks finished faster than.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, platform) (rate(multi_platform_controller_task_run_time_bucket{source_cluster=~\"$cluster\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Task Run Rate",
   "type": "timeseries",
   "description": "The number of tasks completed per second, aggregated by platform.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 76 },
   "targets": [
    {
     "expr": "sum by(platform) (rate(multi_platform_controller_task_run_time_count{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Wait Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Average Task's Wait Time (5m Window)",
   "type": "timeseries",
   "description": "The average wait time for a host to become available, excluding the host allocation time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum by(platform) (rate(multi_platform_controller_wait_time_sum{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m])) / sum by(platform) (rate(multi_platform_controller_wait_time_count{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tasks Per Second Waiting (5m Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum by(platform) (rate(multi_platform_controller_wait_time_count{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median Wait Time by Platform (30m Window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 93 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, platform) (rate(multi_platform_controller_wait_time_bucket{source_cluster=~\"$cluster\", platform=~\"$platform\"}[30m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Host Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Platform Host Allocation Time in Seconds (30m Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum by(platform) (rate(multi_platform_controller_host_allocation_time_sum{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m])) / sum by(platform) (rate(multi_platform_controller_host_allocation_time_count{source_cluster=~\"$cluster\", platform=~\"$platform\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median Host Allocation Time by Platform (30m Window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, platform) (rate(multi_platform_controller_host_allocation_time_bucket{source_cluster=~\"$cluster\", platform=~\"$platform\"}[30m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Allocation Per Second By Platform",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 110 },
   "targets": [
    {
     "expr": "sum by(platform) (rate(multi_platform_controller_host_allocation_time_count{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Total Host Allocation Failure State Changes Per Platform (5m Window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "sum(changes(multi_platform_controller_host_allocation_failures{source_cluster=~\"$cluster\", platform=~\"$platform\"} [5m])) by (platform)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Controller Cleanup Per Platform (5m Window)",
   "type": "timeseries",
   "description": "Count of all cleanup failures that occurred within the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "targets": [
    {
     "expr": "sum(increase(multi_platform_controller_cleanup_failures{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m])) by (platform)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Provisioning Failures Per Platform (5m Window)",
   "type": "timeseries",
   "description": "Count of all provisioning failures that occurred within the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 127 },
   "targets": [
    {
     "expr": "sum(increase(multi_platform_controller_provisioning_failures{source_cluster=~\"$cluster\", platform=~\"$platform\"}[5m])) by (platform)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Invalid Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "multi_platform_controller_cleanup_failures",
   "type": "timeseries",
   "description": "Always zero",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "multi_platform_controller_cleanup_failures",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "multi_platform_controller_provisioning_failures",
   "type": "timeseries",
   "description": "Always zero",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "targets": [
    {
     "expr": "multi_platform_controller_provisioning_failures",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "multi_platform_controller_running_tasks",
   "type": "timeseries",
   "description": "It shouldn't be minus",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 144 },
   "targets": [
    {
     "expr": "multi_platform_controller_running_tasks",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}