{
 "title": "Konflux Kueue-sre",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  { "title": "Kueue Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admission Attempt Latency",
   "type": "heatmap",
   "description": "The latency of an admission attempt.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (increase(kueue_admission_attempt_duration_seconds_bucket{source_cluster=~\"$cluster\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Container Restarts In the Last Hour",
   "type": "stat",
   "gridPos": { "h": 34, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=~\"tekton-kueue|kueue-external-admission|openshift-kueue-operator\", source_cluster=~\"$cluster\"}[1h])\n* on(container, pod)\nkube_pod_container_status_ready{namespace=~\"tekton-kueue|kueue-external-admission|openshift-kueue-operator\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  kube_deployment_status_replicas_available{namespace=~\"openshift-kueue-operator|tekton-kueue|kueue-external-admission\", source_cluster=~\"$cluster\"}\n)\n/\nclamp_min(\n  kube_deployment_spec_replicas{namespace=~\"openshift-kueue-operator|tekton-kueue|kueue-external-admission\", source_cluster=~\"$cluster\"},\n  1\n) * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Admission Latency 99th Percentile",
   "type": "stat",
   "description": "99th Percentile of the latency of an admission attempt.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(kueue_admission_attempt_duration_seconds_bucket{source_cluster=~\"$cluster\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kueue Mutating Webhook Request Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(increase(apiserver_admission_webhook_request_total{name=\"pipelinerun-kueue-defaulter.tekton-kueue.io\", code=~\"2..|400\", source_cluster=~\"$cluster\"}[10m]))\n/\nsum(increase(apiserver_admission_webhook_request_total{name=\"pipelinerun-kueue-defaulter.tekton-kueue.io\", source_cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tekton Kueue CEL evaluations filiaures",
   "type": "stat",
   "description": "Monitor the overall health and usage of CEL expressions in tekton-kueue webhook",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tekton_kueue_cel_evaluations_total{result=\"failure\", source_cluster=~\"$cluster\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource Reservation / Nominal Quota",
     "type": "bargauge",
     "gridPos": { "h": 76, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (resource) (kueue_cluster_queue_resource_reservation{cluster_queue=\"cluster-pipeline-queue\", source_cluster=~\"$cluster\"} /kueue_cluster_queue_nominal_quota{cluster_queue=\"cluster-pipeline-queue\", source_cluster=~\"$cluster\"} * 100)",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Queue Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 12, "y": 99 },
     "targets": [
      {
       "expr": "max by (status) (kueue_cluster_queue_status{cluster_queue=\"cluster-pipeline-queue\", source_cluster=~\"$cluster\"}) == 1",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Pending Workloads",
     "type": "stat",
     "description": "The number of pending workloads",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 99 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (status) (kueue_pending_workloads{cluster_queue=\"cluster-pipeline-queue\", source_cluster=~\"$cluster\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Admitted Workloads Increase",
     "type": "stat",
     "description": "The total number of admitted workloads in the selected range",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 105 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(increase(kueue_admitted_workloads_total{source_cluster=~\"$cluster\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Admitted Active Workloads",
     "type": "stat",
     "description": "The number of admitted Workloads that are active (unsuspended and not finished)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 111 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kueue_admitted_active_workloads{cluster_queue=\"cluster-pipeline-queue\", source_cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Admission Wait Time 99th Percentile ",
     "type": "stat",
     "description": "99% of the workloads waited in the queue less time from the shown value",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(increase(kueue_admission_wait_time_seconds_bucket{cluster_queue=\"cluster-pipeline-queue\", source_cluster=~\"$cluster\"}[$__range])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Admission Wait Time 99th Percentile By Priority Class",
     "type": "stat",
     "description": "99% of the workloads waited in the queue less time from the shown value. Broke into Priority Classes.",
     "gridPos": { "x": 12, "y": 26, "h": 6, "w": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(increase(kueue_admission_wait_time_seconds_bucket{source_cluster=~\"$cluster\", cluster_queue=\"cluster-pipeline-queue\"}[$__range])) by (le, priority_class))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Admitted Workloads Increase By Priority Class",
     "type": "stat",
     "description": "The total number of admitted workloads,  by priority class , in the selected range",
     "gridPos": { "x": 12, "y": 32, "h": 6, "w": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum by (priority_class) (increase(kueue_admitted_workloads_total{source_cluster=~\"$cluster\"}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Resource Usage / Reservation",
     "type": "stat",
     "gridPos": { "h": 36, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (resource) (kueue_cluster_queue_resource_usage{cluster_queue=\"cluster-pipeline-queue\", source_cluster=~\"$cluster\"} / kueue_cluster_queue_resource_reservation{cluster_queue=\"cluster-pipeline-queue\", source_cluster=~\"$cluster\"} * 100)",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Quota Reserved Wait Time",
     "type": "heatmap",
     "description": "The time between a workload was created or requeued until it got quota reservation",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
     "targets": [
      {
       "expr": "sum by (le) (increase(kueue_quota_reserved_wait_time_seconds_bucket{cluster_queue=\"cluster-pipeline-queue\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Admission Wait Time",
     "type": "heatmap",
     "description": "kueue_admission_wait_time_seconds",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
     "targets": [
      {
       "expr": "sum by (le) (increase(kueue_admission_wait_time_seconds_bucket{cluster_queue=\"cluster-pipeline-queue\", source_cluster=~\"$cluster\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Tenants",
     "type": "stat",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 164 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_namespace_labels{container=\"kube-rbac-proxy-main\", source_cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PipelineRun Deletion Duration",
     "type": "heatmap",
     "description": "The duration that watcher take to delete the PipelineRun since completion",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 164 },
     "targets": [
      {
       "expr": "sum by (le) (increase(watcher_pipelinerun_delete_duration_seconds_bucket{source_cluster=~\"$cluster\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Pipeline Deletion Duration 99th Percentile",
     "type": "stat",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (increase(watcher_pipelinerun_delete_duration_seconds_bucket{source_cluster=~\"$cluster\"}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Workloads vs Etcd Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
     "targets": [
      {
       "expr": "max(kueue_admitted_active_workloads{cluster_queue=\"cluster-pipeline-queue\", source_cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(etcd_mvcc_db_total_size_in_use_in_bytes{namespace=\"openshift-etcd\", source_cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Pipelineruns vs Etcd Usage",
     "type": "timeseries",
     "description": "The number of all the Pipelineruns in the cluster (in all states) vs Etcd usage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
     "targets": [
      {
       "expr": "max(apiserver_storage_objects{resource=\"pipelineruns.tekton.dev\", source_cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(etcd_mvcc_db_total_size_in_use_in_bytes{namespace=\"openshift-etcd\", source_cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Efficiency & Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kueue Resource Saturation",
     "type": "timeseries",
     "description": "Description:This metric measures the current resource utilization of the cluster queue as a percentage of its defined nominal quota ($Reservation / Quota * 100$). It provides a high-level view of how much of the allocated capacity (e.g., CPU, Memory, or GPU) is being consumed by admitted workloads.At 100%: The cluster has reached its maximum allowed capacity. New workloads will be held in a Pending state and will not be admitted until existing resources are released.Sustained 100% (Flat Line): When this graph stays at the ceiling for an extended period while the Pending Workloads count remains high, it indicates a bottleneck.The \"Correlation\" Check: If this graph shows 100% saturation but the Workload Admission Gap also shows a high number of \"ghost\" workloads, it confirms a Quota Leak. In this state, the cluster is \"full\" on paper due to stale resources or finalizers, even if the physical infrastructure is underutilized.",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max by (resource, source_cluster) (\n  kueue_cluster_queue_resource_reservation{source_cluster=~\"$cluster\"} \n  / \n  kueue_cluster_queue_nominal_quota{source_cluster=~\"$cluster\"}\n) * 100",
       "legendFormat": "{{resource}} - {{source_cluster}}"
      }
     ]
    },
    {
     "title": "Kueue Workload Admission Gap ",
     "type": "timeseries",
     "description": "This metric calculates the discrepancy between the workloads Kueue has officially admitted into the quota and the workloads currently reported as \"active\" in the cluster queue status.\n\nPositive Value: Indicates a \"Quota Leak.\" Workloads are occupying capacity in the admission controller but are not actively progressing or accounted for in the operational status. This usually points to stale resources, such as PipelineRuns or Workloads stuck with finalizers that prevent them from fully clearing the system.\n\nZero Value: Indicates a healthy state where the admission controller and the cluster queue are in perfect synchronization.\n\nMonitoring this gap is essential for maintaining the software supply chain's throughput, as a persistent gap will block new builds even if physical resources appear available.",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (source_cluster) (kueue_admitted_active_workloads{source_cluster=~\"$cluster\"})\n-\nsum by (source_cluster) (kueue_cluster_queue_status{status=\"active\", source_cluster=~\"$cluster\"})",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Kueue Pending Workloads",
     "type": "timeseries",
     "description": "Description:\nThis metric tracks the total number of workloads currently waiting in the queue to be admitted and executed across the specified clusters. It serves as a primary indicator of Queue\nKey Indicators:\n\nValue = 0: Healthy state. All admitted workloads are actively running. Any wait times observed are due to genuine resource congestion.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (source_cluster) (kueue_pending_workloads{source_cluster=~\"$cluster\"})",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Pre-Merge/Post-Merge Build Admission Wait Time",
     "type": "timeseries",
     "description": "This metric calculates the median (P50) wait time in minutes for critical CI workloads, specifically those assigned to the konflux-post-merge-build priority class. It represents the time elapsed from the moment a workload is created until it is admitted for execution by Kueue.\n\nPurpose: This is a \"Quality of Service\" (QoS) metric for the developer experience. Since merge-related builds are on the critical path for code integration, they require low latency. High values here directly translate to developer frustration and slower delivery cycles.\n\nAlerting Logic: The system is tuned with a tight threshold of 15 minutes.\n\nNormal State: Values should stay well below the 15-minute mark.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le, source_cluster) (\n  rate(kueue_admission_wait_time_seconds_bucket{\n    priority_class=\"konflux-post-merge-build\", \n    source_cluster=~\"$cluster\"\n  }[5m])\n)) / 60",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Mintmaker Admission Wait Time",
     "type": "timeseries",
     "description": "Description:\nThis metric calculates the median (P50) wait time in hours for workloads under the konflux-dependency-update priority class. It measures how long these non-critical jobs stay in the queue before being admitted to a cluster.\n\nPurpose: Since dependency updates (like those from Mintmaker/Renovate) are low-priority, they are expected to wait during peak traffic. This graph ensures they aren't being completely starved for resources.\n\nAlerting Logic: In a healthy state, this value may fluctuate significantly depending on cluster load. We set a high threshold (12 hours) to avoid noise; an alert is only triggered if the wait time exceeds half a day, indicating a serious long-term capacity issue or a \"starvation\" scenario where high-priority jobs never leave room for lower ones.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le, source_cluster) (\n  rate(kueue_admission_wait_time_seconds_bucket{\n    priority_class=\"konflux-dependency-update\", \n    source_cluster=~\"$cluster\"\n  }[15m])\n)) / 3600",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Mintmaker Time since last trigger",
     "type": "timeseries",
     "description": "Time elapsed since last DUC creation\n\nThe Logic: It subtracts the actual running workloads from the admitted count. In a healthy cluster, this gap should be near zero.\n\nThe \"Leak\": A persistent, high value (e.g., 200+) indicates a Quota Leak. This happens when stale workloads or stuck finalizers occupy \"virtual\" space in the quota, preventing new jobs from starting even if physical resources are available.\n\nExecutive Insight: This graph proves that high wait times for low-priority tasks aren't always caused by lack of hardware, but by \"ghost\" workloads that need automated cleanup.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "targets": [
      {
       "expr": "(time() - max by(source_cluster) (mintmaker_dependency_update_check_creation_time{source_cluster=~\"$cluster\"})) / 3600",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    }
   ]
  }
 ]
}