{
 "title": "Cluster Capacity",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Master Node Overview", "type": "text", "description": "Cluster node metrics.", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Master Node with Highest Memory Usage",
   "type": "barchart",
   "description": "Master Node with highest memory usage in each cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(1, \nmax by (source_cluster,instance) (\n    100 * ((node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"} - node_memory_MemAvailable_bytes{source_cluster=~\"$cluster\"}) / node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"})\n  ) and on (instance) \nlabel_replace( kube_node_role{role=\"master\"}, \"instance\", \"$1\", \"node\", \"(.+)\" )) by (source_cluster)",
     "legendFormat": "{{source_cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "Master Node with Highest CPU Usage",
   "type": "barchart",
   "description": "Master Node with highest CPU usage in each cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(1, \n100 * max by (source_cluster,instance) (1 - rate(node_cpu_seconds_total{mode=\"idle\",source_cluster=~\"$cluster\"}[5m]) \nand on (instance) \nlabel_replace( kube_node_role{role=\"master\"}, \"instance\", \"$1\", \"node\", \"(.+)\" ))\n)  by (source_cluster)",
     "legendFormat": "{{source_cluster}} {{instance}}"
    }
   ]
  },
  { "title": "Infra Node Overview", "type": "text", "description": "Cluster Infra node metrics.", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Infra Node with Highest Memory Usage",
   "type": "barchart",
   "description": "Infra Node with highest memory usage in each cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(1, \nmax by (source_cluster,instance) (\n    100 * ((node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"} - node_memory_MemAvailable_bytes{source_cluster=~\"$cluster\"}) / node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"})\n  ) and on (instance) \nlabel_replace( kube_node_role{role=\"infra\"}, \"instance\", \"$1\", \"node\", \"(.+)\" )) by (source_cluster)",
     "legendFormat": "{{source_cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "Infra Node with Highest CPU Usage",
   "type": "barchart",
   "description": "Infra Node with highest CPU usage in each cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(1, \n100 * max by (source_cluster,instance) (1 - rate(node_cpu_seconds_total{mode=\"idle\",source_cluster=~\"$cluster\"}[5m]) \nand on (instance) \nlabel_replace( kube_node_role{role=\"infra\"}, \"instance\", \"$1\", \"node\", \"(.+)\" ))\n)  by (source_cluster)",
     "legendFormat": "{{source_cluster}} {{instance}}"
    }
   ]
  },
  { "title": "Worker Node Overview", "type": "text", "description": "Worker node metrics.", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Worker Node with Highest Memory Usage",
   "type": "barchart",
   "description": "Worker Node with highest memory usage in each cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(1, \nmax by (source_cluster,instance) (\n    100 * ((node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"} - node_memory_MemAvailable_bytes{source_cluster=~\"$cluster\"}) / node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"})\n  ) and on (instance) \nlabel_replace( kube_node_role{role=\"worker\"}, \"instance\", \"$1\", \"node\", \"(.+)\" )) by (source_cluster)",
     "legendFormat": "{{source_cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "Worker Node with Highest CPU Usage",
   "type": "barchart",
   "description": "Worker Node with highest CPU usage in each cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(1, \n100 * max by (source_cluster,instance) (1 - rate(node_cpu_seconds_total{mode=\"idle\",source_cluster=~\"$cluster\"}[5m]) \nand on (instance) \nlabel_replace( kube_node_role{role=\"worker\"}, \"instance\", \"$1\", \"node\", \"(.+)\" ))\n)  by (source_cluster)",
     "legendFormat": "{{source_cluster}} {{instance}}"
    }
   ]
  },
  { "title": "ETCD Overview", "type": "text", "description": "Key ETCD metrics.", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "ETCD Instances Up",
   "type": "bargauge",
   "description": "Number of ETCD instances per cluster.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{job=\"etcd\",source_cluster=~\"$cluster\"}) by (source_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD Intances with Highest Database Usage",
   "type": "barchart",
   "description": "ETCD instances with highest database usage per cluster sorted in descending order.",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_desc(topk(1, \n  max by (source_cluster, instance) (\n    (last_over_time(etcd_mvcc_db_total_size_in_bytes{job=\"etcd\",source_cluster=~\"$cluster\"}[5m]) / last_over_time(etcd_server_quota_backend_bytes{job=\"etcd\",source_cluster=~\"$cluster\"}[5m])*100)\n  )\n)  by (source_cluster))",
     "legendFormat": "{{source_cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "ETCD Shield",
   "type": "stat",
   "description": "When stats report a value above 0, ETCD Shield is triggered.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_shield_alert_triggered{source_cluster=~\"$cluster\"}) by (source_cluster)",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "ETCD Defragmentation Heatmap",
   "type": "heatmap",
   "description": "Heatmap of ETCD defragmentation counts per cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(etcd_disk_defrag_inflight{source_cluster=~\"$cluster\"}) by (source_cluster)",
     "legendFormat": "{{source_cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "Tekton Pipelinerun Overview",
   "type": "text",
   "description": "Tekton Pipelinerun metrics per cluster.",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "Running Pipelineruns Hourly Rate Heatmap",
   "type": "heatmap",
   "description": "A Heatmap of hourly rate of running Pipelineruns per cluster.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(tekton_pipelines_controller_running_pipelineruns{source_cluster=~\"$cluster\"}[1h])) by (source_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dashboard Reference",
   "type": "text",
   "description": "Standard Operation Procedure dashboard reference.",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }
  },
  {
   "title": "Node Memory Usage Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Control Plane Nodes  Memory Usage",
     "type": "timeseries",
     "description": "Cluster Control Plane Nodes memory usage.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (source_cluster,instance) (\n    100 * ((node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"} - node_memory_MemAvailable_bytes{source_cluster=~\"$cluster\"}) / node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"})\n  ) and on (instance) \nlabel_replace( kube_node_role{role=\"master\"}, \"instance\", \"$1\", \"node\", \"(.+)\" )",
       "legendFormat": "{{source_cluster}} master node {{instance}}"
      },
      {
       "expr": "avg by (source_cluster,instance) (\n    100 * ((node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"} - node_memory_MemAvailable_bytes{source_cluster=~\"$cluster\"}) / node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"})\n  ) and on (instance) \nlabel_replace( kube_node_role{role=\"infra\"}, \"instance\", \"$1\", \"node\", \"(.+)\" )",
       "legendFormat": "{{source_cluster}} infra node {{instance}}"
      }
     ]
    },
    {
     "title": "Cluster Worker Nodes  Memory Usage",
     "type": "timeseries",
     "description": "Worker Nodes memory usage.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 292 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (source_cluster,instance) (\n    100 * ((node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"} - node_memory_MemAvailable_bytes{source_cluster=~\"$cluster\"}) / node_memory_MemTotal_bytes{source_cluster=~\"$cluster\"})\n  ) and on (instance) \nlabel_replace( kube_node_role{role=\"worker\"}, \"instance\", \"$1\", \"node\", \"(.+)\" )",
       "legendFormat": "{{source_cluster}} worker node {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node CPU Usage Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Control Plane Nodes CPU Usage",
     "type": "timeseries",
     "description": "Master and Infra Nodes CPU usage.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * avg by (source_cluster,instance) (1 - rate(node_cpu_seconds_total{mode=\"idle\",source_cluster=~\"$cluster\"}[5m]) \nand on (instance) \nlabel_replace( kube_node_role{role=\"master\"}, \"instance\", \"$1\", \"node\", \"(.+)\" ))",
       "legendFormat": "{{source_cluster}} master node {{instance}}"
      },
      {
       "expr": "100 * avg by (source_cluster,instance) (1 - rate(node_cpu_seconds_total{mode=\"idle\",source_cluster=~\"$cluster\"}[5m]) \nand on (instance) \nlabel_replace( kube_node_role{role=\"infra\"}, \"instance\", \"$1\", \"node\", \"(.+)\" ))",
       "legendFormat": "{{source_cluster}} infra node {{instance}}"
      }
     ]
    },
    {
     "title": "Cluster Worker CPU Usage",
     "type": "timeseries",
     "description": "Worker Nodes CPU usage.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 295 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * avg by (source_cluster,instance) (1 - rate(node_cpu_seconds_total{mode=\"idle\",source_cluster=~\"$cluster\"}[5m]) \nand on (instance) \nlabel_replace( kube_node_role{role=\"worker\"}, \"instance\", \"$1\", \"node\", \"(.+)\" ))",
       "legendFormat": "{{source_cluster}} worker node {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipelineruns Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Pipelineruns Hourly Rate",
     "type": "timeseries",
     "description": "Hourly rate of running Pipelineruns per cluster.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum(rate(tekton_pipelines_controller_running_pipelineruns{source_cluster=~\"$cluster\"}[1h])) by (source_cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rejected PipelineRuns",
     "type": "timeseries",
     "description": "Rejected PipelineRuns due to etcd-shield triggered.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "sum(increase(apiserver_admission_webhook_rejection_count\n{name=\"vpipelineruns.konflux-ci.dev\"}[1h])) by (source_cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ETCD Shield",
     "type": "timeseries",
     "description": "When stats report a value above 0, ETCD Shield is triggered.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(etcd_shield_alert_triggered{source_cluster=~\"$cluster\"}) by (source_cluster)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ETCD Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "ETCD DB Usage",
     "type": "timeseries",
     "description": "Database usage per ETCD instance.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(last_over_time(etcd_mvcc_db_total_size_in_bytes{job=\"etcd\",source_cluster=~\"$cluster\"}[5m]) / last_over_time(etcd_server_quota_backend_bytes{job=\"etcd\",source_cluster=~\"$cluster\"}[5m]))*100 ",
       "legendFormat": "{{source_cluster}} {{instance}}"
      }
     ]
    },
    {
     "title": "ETCD Defragmentation",
     "type": "timeseries",
     "description": "Total ETCD defragmentation operations per cluster.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(etcd_disk_defrag_inflight{source_cluster=~\"$cluster\"}) by (source_cluster)",
       "legendFormat": "{{source_cluster}} {{instance}}"
      }
     ]
    },
    {
     "title": "ETCD Server Leader Changes Increase",
     "type": "timeseries",
     "description": "Increase of number ETCD leader changes over the past 10 minutes.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(etcd_server_leader_changes_seen_total{namespace=\"openshift-etcd\",source_cluster=~\"$cluster\"}[10m])",
       "legendFormat": "{{source_cluster}} {{instance}}"
      }
     ]
    },
    {
     "title": "ETCD Number of Members",
     "type": "timeseries",
     "description": "Number of ETCD members per cluster.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(etcd_server_id{source_cluster=~\"$cluster\"}) by (source_cluster)",
       "legendFormat": "{{source_cluster}} {{instance}}"
      }
     ]
    },
    {
     "title": "ETCD Server Has No Leader",
     "type": "timeseries",
     "description": "Graph indicates in red threshold when there's no etcd leader.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "(1 - etcd_server_has_leader{source_cluster=~\"$cluster\"})",
       "legendFormat": "{{source_cluster}} {{instance}}"
      }
     ]
    },
    {
     "title": "ETCD Server Proposals Failed Hourly Rate",
     "type": "timeseries",
     "description": "Etcd high number of failed proposals on pods",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(etcd_server_proposals_failed_total{source_cluster=~\"$cluster\"}[1h])",
       "legendFormat": "{{source_cluster}} {{instance}}"
      }
     ]
    },
    {
     "title": "ETCD Disk Sync Duration",
     "type": "timeseries",
     "description": "The 99th percentile of ETCD's disk backend commit duration over the last 24 minutes, calculated per instance, indicates the time within which 99% of these operations were completed.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"etcd\",source_cluster=~\"$cluster\"}[24m])) by (instance, le))",
       "legendFormat": "{{source_cluster}} {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\"}[24m])) by (instance, le))",
       "legendFormat": "{{source_cluster}} {{instance}}"
      }
     ]
    },
    {
     "title": "Etcd Commit Latency",
     "type": "timeseries",
     "description": "10 minutes average of 99th etcd commit latency higher than 40ms in cluster.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"etcd\",source_cluster=~\"$cluster\"}[2m]))[10m:]) ",
       "legendFormat": "{{source_cluster}} {{instance}}"
      }
     ]
    },
    {
     "title": "Etcd High Fsync Durations",
     "type": "timeseries",
     "description": "99th percentile of the etcd WAL fsync durations over the last 5 minutes. Provides insight into the disk I/O performance.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\",source_cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "{{source_cluster}} {{instance}}"
      }
     ]
    },
    {
     "title": " Etcd Number of Failed GRPC Requests",
     "type": "timeseries",
     "description": "Percentage of failed ETCD gRPC requests over the last 5 minutes when request per second are above 2 req/s and excluded Installer Provisioned Infrastructure and Bare metal cluster setups.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(sum without (grpc_type, grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Unknown|FailedPrecondition|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded\",job=\"etcd\",source_cluster=~\"$cluster\"}[5m])) / (sum without (grpc_type, grpc_code) (rate(grpc_server_handled_total{job=\"etcd\",source_cluster=~\"$cluster\"}[5m])) > 2 and on () (sum(cluster_infrastructure_provider{type!~\"ipi|BareMetal\"} == bool 1)))) * 100",
       "legendFormat": "{{source_cluster}} {{instance}} {{grpc_method}} {{grpc_service}}"
      }
     ]
    },
    {
     "title": "Etcd GRPC requests slow",
     "type": "timeseries",
     "description": "99th percentile of gRPC server handling durations within the openshift-etcd namespace. It aggregates the request rates by source cluster, gRPC service, and method to provide a view of latency distribution.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"openshift-etcd\",source_cluster=~\"$cluster\"}[1m])) by (source_cluster,grpc_service, grpc_method, le))",
       "legendFormat": "{{source_cluster}} {{grpc_service}} {{grpc_method}}"
      }
     ]
    }
   ]
  }
 ]
}