{
 "title": "Internal Services breakdown",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits{namespace=\"stonesoup-int-srvc\", container=\"manager\"},pod)"
    }
   },
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Internal Services Breakdown dashboard"
   }
  },
  {
   "title": "IR Pods in the namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(job) (kube_pod_container_info {namespace=\"stonesoup-int-srvc\", pod=~\"internalrequest.*pod\"})",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "succeeded pipelineruns duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds{namespace=\"stonesoup-int-srvc\", status=\"success\"}) by(pipeline)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Requests Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Internal Requests Cleanup job",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_failed{namespace=\"stonesoup-int-srvc\", job_name=~\"cleanup-internal-requests-pipelineruns-.*\", condition=\"true\"})",
       "legendFormat": "failed"
      },
      {
       "expr": "sum (kube_job_complete{namespace=\"stonesoup-int-srvc\", job_name=~\"cleanup-internal-requests-pipelineruns-.*\"})",
       "legendFormat": "succeeded"
      }
     ]
    },
    {
     "title": "Signature Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "sum(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds{namespace=\"stonesoup-int-srvc\", task=\"request-and-upload-signature\" }) by (task,status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "succeeded taskruns duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds{namespace=\"stonesoup-int-srvc\", status=\"success\" }) by (task)",
       "legendFormat": "{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "pods in the namespace",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=\"stonesoup-int-srvc\", container!=\"manager\"})",
       "legendFormat": "waiting"
      },
      {
       "expr": "sum(kube_pod_status_ready{namespace=\"stonesoup-int-srvc\", condition=\"true\"} > 0)",
       "legendFormat": "running"
      },
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=\"stonesoup-int-srvc\", container!=\"manager\"}) +\nsum(kube_pod_status_ready{namespace=\"stonesoup-int-srvc\", condition=\"true\"} > 0)",
       "legendFormat": "all pods"
      }
     ]
    },
    {
     "title": "Signature Requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum(kube_pod_status_phase{namespace=\"stonesoup-int-srvc\", pod=~\".*request-signature-pod\"}) by(phase))",
       "legendFormat": "requested"
      },
      {
       "expr": "sum(sum(kube_pod_status_phase{namespace=\"stonesoup-int-srvc\", pod=~\".*upload-signature-pod\"}) by(phase))",
       "legendFormat": "received"
      },
      {
       "expr": "(\n    (sum(sum(kube_pod_status_phase{namespace=\"stonesoup-int-srvc\", pod=~\".*request-signature-pod\"}) by(phase)))\n    - \n    (sum(sum(kube_pod_status_phase{namespace=\"stonesoup-int-srvc\", pod=~\".*upload-signature-pod\"}) by(phase)))\n) ",
       "legendFormat": "waiting"
      }
     ]
    },
    {
     "title": "pods in the namespace",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=\"stonesoup-int-srvc\", container!=\"manager\"})",
       "legendFormat": "waiting pods"
      },
      {
       "expr": "sum(kube_pod_status_ready{namespace=\"stonesoup-int-srvc\", condition=\"true\"} > 0)",
       "legendFormat": "running pods"
      }
     ]
    },
    {
     "title": "namespace memory usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "namespace:container_memory_usage_bytes:sum{namespace=\"stonesoup-int-srvc\"}",
       "legendFormat": "used"
      },
      {
       "expr": "sum(kube_limitrange{namespace=\"stonesoup-int-srvc\", type=\"Pod\", resource=\"memory\"}) by (constraint)",
       "legendFormat": "{{constraint}}"
      }
     ]
    },
    {
     "title": "namespace cpu usage",
     "type": "timeseries",
     "description": "graph in logarithmic mode for better viewing",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", namespace=\"stonesoup-int-srvc\"}[5m])) by (namespace)",
       "legendFormat": "used"
      },
      {
       "expr": "sum(kube_limitrange{namespace=\"stonesoup-int-srvc\",  type=\"Container\", resource=\"cpu\", constraint=~\"default|defaultRequest|max\"}) by(constraint)",
       "legendFormat": "{{constraint}}"
      }
     ]
    },
    {
     "title": "CPU throttled seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"stonesoup-int-srvc\", container!=\"\"}[$interval]) ) by(pod,container)",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU / Memory Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "manager cpu usage ($pod)",
   "type": "timeseries",
   "description": "graph in logarithmic scale for better viewing",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum (rate (container_cpu_usage_seconds_total{namespace=\"stonesoup-int-srvc\", container=\"manager\", pod=~\"$pod\"}[$interval])) by (container))",
     "legendFormat": "used"
    },
    {
     "expr": "(max(kube_pod_container_resource_limits{namespace=\"stonesoup-int-srvc\", container=\"manager\", resource=\"cpu\", pod=~\"$pod\"}) by(container)) ",
     "legendFormat": "limits"
    },
    {
     "expr": "(max(kube_pod_container_resource_requests{namespace=\"stonesoup-int-srvc\", container=\"manager\", resource=\"cpu\", pod=~\"$pod\"}) by(container))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "manager memory usage ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"stonesoup-int-srvc\", container=\"manager\", pod=~\"$pod\"}) by(container)",
     "legendFormat": "used"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"stonesoup-int-srvc\", container=\"manager\", resource=\"memory\", pod=~\"$pod\"}) by(container)",
     "legendFormat": "limits"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"stonesoup-int-srvc\", container=\"manager\", resource=\"memory\", pod=~\"$pod\"}) by(container)",
     "legendFormat": "requests"
    }
   ]
  }
 ]
}