{
 "title": "Konflux - Integration Service SLI's",
 "tags": [
  "konflux",
  "integration-service",
  "SLI's"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(konflux_up,service)"
    }
   },
   {
    "name": "check",
    "query": {
     "query": "label_values(konflux_up{service=~\"$service\"},check)"
    }
   },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Snapshot Attempts Total",
   "type": "timeseries",
   "description": "Total number of snapshots processed by the operator",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(integration_svc_snapshot_attempt_total[$__rate_interval])",
     "legendFormat": "{{source_cluster}} - {{reason}} "
    }
   ]
  },
  {
   "title": "Total Integration PipelineRuns",
   "type": "timeseries",
   "description": "The total number of new integration PipelineRuns that have started in each cluster over the selected time range",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (increase(integration_svc_integration_pipelinerun_total{source_cluster=~\"$cluster\"}[$__interval]))\n",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "description": "The number of items waiting to be processed, snapshots or integration test scenarios. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "workqueue_depth{name=\"snapshot\", namespace=\"integration-service\"}\n",
     "legendFormat": "{{source_cluster}} - {{name}}"
    },
    {
     "expr": "workqueue_depth{name=\"integrationtestscenario\", namespace=\"integration-service\"}",
     "legendFormat": "{{source_cluster}} - {{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Duration Seconds",
   "type": "timeseries",
   "description": "95% of requests, either snapshots or IntegrationTestScenarios, finished in this amount of time or less",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum by(le, source_cluster, name) (rate(workqueue_queue_duration_seconds_bucket{name=~\"snapshot|integrationtestscenario\", namespace=\"integration-service\"}[$__rate_interval])))\n\n",
     "legendFormat": "{{source_cluster}} - {{name}}"
    }
   ]
  },
  {
   "title": "Github App Availability",
   "type": "timeseries",
   "description": "Uptime percentage of the connection to the GitHub application, as measured by the integration service, over the last 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(redhat_appstudio_integrationservice_global_github_app_available{source_cluster=~\"$cluster\"}[24h]) * 100",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  }
 ]
}