{
 "title": "Konflux Probes",
 "description": "Blackbox Exporter Probes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(source_cluster)" } },
   {
    "name": "probe",
    "label": "probe",
    "query": {
     "query": "label_values(probe_success{source_cluster=~\"$cluster\", job!~\"ibm-.*\"},job)"
    }
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success{job=~\"$probe\"},target)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Probe Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Probe Count",
   "type": "stat",
   "description": "Number of selected probes per cluster",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (source_cluster) (probe_success{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\"})",
     "legendFormat": "{{job}} {{target}} {{source_cluster}}"
    }
   ]
  },
  {
   "title": "Probe Status",
   "type": "state-timeline",
   "description": "Probe Status by probe group, probe path and cluster",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\"}",
     "legendFormat": "{{job}} {{target}} {{source_cluster}}"
    }
   ]
  },
  {
   "title": "Probe Group Status",
   "type": "table",
   "description": "Last Probe Status by group of probes",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by (job,source_cluster) (probe_success{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\"}) / count by (job,source_cluster) (probe_success{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\"})",
     "legendFormat": "{{job}} {{target}} {{source_cluster}}"
    }
   ]
  },
  {
   "title": "Highest Probe Duration",
   "type": "barchart",
   "description": "Top 10 highest of average probe duration in seconds over 5 minutes",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, avg_over_time(probe_duration_seconds{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\"}[5m])))",
     "legendFormat": " {{source_cluster}} {{job}} {{target}}"
    }
   ]
  },
  { "title": "Probe Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Probe Status",
   "type": "timeseries",
   "description": "Time Series Graph of probe status",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_success{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\"}",
     "legendFormat": "{{source_cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "description": "Probe duration in seconds",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{source_cluster=~\"$cluster\",target=~\"$target\",job=~\"$probe\"}",
     "legendFormat": "{{source_cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "Probe DNS Lookup Duration",
   "type": "timeseries",
   "description": "DNS lookup duration in seconds",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{source_cluster=~\"$cluster\",target=~\"$target\"}",
     "legendFormat": "{{source_cluster}} {{instance}} "
    }
   ]
  }
 ]
}