{
 "title": "Konflux - Integration Service SLO",
 "tags": [
  "konflux",
  "integration-service",
  "SLO's"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(konflux_up,service)"
    }
   },
   {
    "name": "check",
    "query": {
     "query": "label_values(konflux_up{service=~\"$service\"},check)"
    }
   },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Integration Service read replica availability - overall",
   "type": "gauge",
   "description": "The system's overall read replica availability percentage for the timeframe selected.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(count_over_time((konflux_up{service=~\"$service\", source_cluster=~\"$cluster\"} == 1)[$__range:]) / count_over_time(konflux_up{service=~\"$service\", source_cluster=~\"$cluster\"}[$__range:])) * 100",
     "legendFormat": "Global Average Uptime"
    }
   ]
  },
  {
   "title": "Integration Service read replica availability per cluster",
   "type": "gauge",
   "description": "Read replica availability percentage of Integration Service on each cluster for the timeframe selected.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(konflux_up{namespace=\"integration-service\", check=\"replicas-available\", service=\"integration-service-controller-manager\"}[24h]) * 100",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "Integration Service read replica availability per cluster",
   "type": "timeseries",
   "description": "Integration Service read replica availability per cluster for timeframe selected",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( (count_over_time(group by (service, check, source_cluster) (konflux_up{service=~\"$service\", check=~\"$check\", source_cluster=~\"$cluster\"} == 1)[$__range:])) / (count_over_time(group by (service, check, source_cluster) (konflux_up{service=~\"$service\", check=~\"$check\", source_cluster=~\"$cluster\"})[$__range:])) ) * 100",
     "legendFormat": "{{source_cluster}} - {{service}} - {{check}} "
    }
   ]
  },
  {
   "title": "#1 Latency - Build PLR to Snapshot In Progress",
   "type": "timeseries",
   "description": "Latency (Left Axis): P90 response time. Spikes in the red zone are > 30 sec, indicating a violation of the target service level.\n\nSaturation (Right Axis): The white dashed line indicates 80% saturation. This represents the percentage of requests hitting the maximum measurable delay (20m).\n\nNote: Use the saturation line to identify if a spike is caused by total cluster exhaustion rather than isolated service slowness.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le, source_cluster) (rate(integration_svc_response_seconds_bucket{source_cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{source_cluster}}"
    },
    {
     "expr": "(sum by (source_cluster) (rate(integration_svc_response_seconds_bucket{le=\"+Inf\", source_cluster=~\"$cluster\"}[$__rate_interval])) - sum by (source_cluster) (rate(integration_svc_response_seconds_bucket{le=\"1200.0\", source_cluster=~\"$cluster\"}[$__rate_interval]))) / sum by (source_cluster) (rate(integration_svc_response_seconds_count{source_cluster=~\"$cluster\"}[$__rate_interval])) * 100",
     "legendFormat": "Saturation {{source_cluster}}"
    }
   ]
  },
  {
   "title": "[Violations] #1 Latency - Build PLR to Snapshot In Progress",
   "type": "timeseries",
   "description": "90% of requests must take less than 30 sec. This panel displays the success rate. A violation occurs when the rate falls below the 90% threshold (below the red line)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (rate(integration_svc_snapshot_created_to_pipelinerun_started_seconds_bucket{le=\"30.0\", source_cluster=~\"$cluster\"}[$__rate_interval])) / sum by (source_cluster) (rate(integration_svc_snapshot_created_to_pipelinerun_started_seconds_count{source_cluster=~\"$cluster\"}[$__rate_interval]))\n* 100",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "#2A Time to Start PipelineRun",
   "type": "timeseries",
   "description": "Measure the time between ApplicationSnapshot creation to pipelineRun creation. Spikes in the red zone are > 5 sec\n\nSaturation (Right Axis): The white dashed line indicates 80% saturation. This represents the percentage of requests hitting the maximum measurable delay (20m).\n\nNote: Use the saturation line to identify if a spike is caused by total cluster exhaustion rather than isolated service slowness.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum by(le, source_cluster) (rate(integration_svc_snapshot_created_to_pipelinerun_started_seconds_bucket{source_cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{source_cluster}}"
    },
    {
     "expr": "(sum by (source_cluster) (rate(integration_svc_snapshot_created_to_pipelinerun_started_seconds_bucket{le=\"+Inf\", source_cluster=~\"$cluster\"}[$__rate_interval])) - sum by (source_cluster) (rate(integration_svc_snapshot_created_to_pipelinerun_started_seconds_bucket{le=\"1200.0\", source_cluster=~\"$cluster\"}[$__rate_interval]))) / sum by (source_cluster) (rate(integration_svc_snapshot_created_to_pipelinerun_started_seconds_count{source_cluster=~\"$cluster\"}[$__rate_interval])) * 100",
     "legendFormat": "Saturation {{source_cluster}}"
    }
   ]
  },
  {
   "title": "[Violations] #2A Time to Start PipelineRun",
   "type": "timeseries",
   "description": "90% of requests must take less than 5sec. This panel displays the success rate. A violation occurs when the rate falls below the 90% threshold (below the red line)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (rate(integration_svc_snapshot_created_to_pipelinerun_started_seconds_bucket{le=\"5.0\", source_cluster=~\"$cluster\"}[$__rate_interval])) / sum by (source_cluster) (rate(integration_svc_snapshot_created_to_pipelinerun_started_seconds_count{source_cluster=~\"$cluster\"}[$__rate_interval])) * 100",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "#5 Latency of Release Creation",
   "type": "timeseries",
   "description": "Measure release creation latency from end of testing to release created. Spikes in the red zone are > 10 sec",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le, source_cluster)(rate(integration_svc_release_latency_seconds_bucket{source_cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "[Violations] #5 Latency of Release Creation",
   "type": "timeseries",
   "description": "90% of requests must take less than 10 sec. This panel displays the success rate. A violation occurs when the rate falls below the 90% threshold (below the red line)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (rate(integration_svc_release_latency_seconds_bucket{le=\"10.0\", source_cluster=~\"$cluster\"}[$__rate_interval])) / sum by (source_cluster) (rate(integration_svc_release_latency_seconds_count{source_cluster=~\"$cluster\"}[$__rate_interval]))* 100",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  }
 ]
}