{
 "title": "OOM Dashboard",
 "tags": [
  "pod-analysis",
  "oom",
  "memory",
  "cpu",
  "tenant",
  "resource-management"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(source_cluster)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OOM Analysis Overview (Memory kill events)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "OOMKilled",
   "type": "stat",
   "description": "Containers in OOMKilled state",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count by (source_cluster, namespace, pod) (\n    max_over_time(\n      kube_pod_container_status_terminated_reason{source_cluster=~\"$cluster\", namespace=~\"$namespace\", reason=\"OOMKilled\"}[$__range]\n    ) > 0\n  )\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOMKilled Containers (Tekton Task Steps)",
   "type": "timeseries",
   "description": "This panel tracks the number of unique containers/tekton task steps terminated due to OOMKilled.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (container) (\n  last_over_time(\n    kube_pod_container_status_terminated_reason{source_cluster=~\"$cluster\", namespace=~\"$namespace\", reason=\"OOMKilled\"}[$__interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOMKilled Pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (source_cluster, namespace, pod, container, node) (\n  max_over_time(\n    kube_pod_container_status_terminated_reason{source_cluster=~\"$cluster\", namespace=~\"$namespace\", reason=\"OOMKilled\"}[$__range]\n  )\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Info",
   "type": "table",
   "description": "Due to impact on cardinality this is just for some enabled namespaces for this high cardinality metric. (until a recording rule is made specific for OOMKills)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "node_namespace_pod:kube_pod_info:{source_cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOM Trend (Range-over-Range)",
   "type": "timeseries",
   "description": "OOMKilled containers over time. The Range desired can be set as the time range of the dashboard",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(\n  max_over_time(\n    {__name__=~\"kube_pod_container_status_(last_terminated|terminated)_reason\", source_cluster=~\"$cluster\", namespace=~\"$namespace\", reason=\"OOMKilled\"}[$__range]\n  )\n) or vector(0)",
     "legendFormat": "This Time Period"
    },
    {
     "expr": "sum(\n  max_over_time(\n    {__name__=~\"kube_pod_container_status_(last_terminated|terminated)_reason\", source_cluster=~\"$cluster\", namespace=~\"$namespace\", reason=\"OOMKilled\"}[$__range] offset $__range\n  )\n) or vector(0)",
     "legendFormat": "Last Time Period"
    }
   ]
  },
  {
   "title": "OOM Namespaces Analysis (Best to filter by cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }
  },
  {
   "title": "Affected Namespaces",
   "type": "stat",
   "description": "Number of unique namespaces with OOMKilled containers",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  count by (namespace, pod) (\n    max_over_time(\n      kube_pod_container_status_terminated_reason{source_cluster=~\"$cluster\", namespace=~\"$namespace\", reason=\"OOMKilled\"}[$__range]\n    ) > 0\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOM by Namespace Over Time",
   "type": "timeseries",
   "description": "This time series tracks the volume of OOMKilled events aggregated. It visualizes memory pressure trends across the environment, helping to distinguish between isolated failures and systemic, cluster-wide resource contention.",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source_cluster, namespace) (\n  kube_pod_container_status_terminated_reason{source_cluster=~\"$cluster\", namespace=~\"$namespace\", reason=\"OOMKilled\"})\n",
     "legendFormat": "{{namespace}} ({{source_cluster}})"
    }
   ]
  },
  {
   "title": "Top 10 Namespaces by OOM",
   "type": "bargauge",
   "description": "Top 10 namespaces with the most OOMKilled containers",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (source_cluster, namespace) (\n    count by (source_cluster, namespace, pod) (\n      max_over_time(\n        kube_pod_container_status_terminated_reason{source_cluster=~\"$cluster\", namespace=~\"$namespace\", reason=\"OOMKilled\"}[$__range]\n      ) > 0\n    )\n  )\n)",
     "legendFormat": "{{source_cluster}}/{{namespace}}"
    }
   ]
  },
  {
   "title": "OOM Repeat offenders (Best to filter by namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }
  },
  {
   "title": "Top 10 Recent Container/TektonTaskSteps terminated by OOM",
   "type": "table",
   "description": "Top 10 OOMKilled Tekton Task (container names)",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (source_cluster, namespace, pod, container) (\n    last_over_time(\n      timestamp(\n        kube_pod_container_status_terminated_reason{source_cluster=~\"$cluster\", namespace=~\"$namespace\", reason=\"OOMKilled\"} == 1\n      )[$__range:]\n    )\n  )\n) * 1000",
     "legendFormat": "{{source_cluster}}/{{namespace}}/{{container}}"
    }
   ]
  },
  {
   "title": "Top 10 OOMKilled Containers/TektonTaskSteps",
   "type": "bargauge",
   "description": "This leaderboard identifies the top 10 containers/tekton tasks with the highest frequency of OOMKilled events within the selected $cluster and $namespace. It uses an Instant query to aggregate the total occurrences over the entire $__range.",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (container) (\n    count by (container, pod) (\n      last_over_time(\n        kube_pod_container_status_terminated_reason{\n          source_cluster=~\"$cluster\", \n          namespace=~\"$namespace\", \n          reason=\"OOMKilled\"\n        }[$__range]\n      )\n    )\n  ) > 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Pressure (Best to filter by namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 }
  },
  {
   "title": "High Memory Utilization (>85% of Limit)",
   "type": "table",
   "description": "Containers using more than 80% of their memory limit",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (source_cluster, namespace, pod, container) (\n    container_memory_usage_bytes{source_cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\"}\n    )\n  /\n  sum by (source_cluster, namespace, pod, container) (\n    kube_pod_container_resource_limits{source_cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\", container!=\"\"}\n    )\n) * 100 > 85",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers/TektonTaskSteps Without Memory Limits (Risk)",
   "type": "table",
   "description": "Containers running without memory limits",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "count by (container, namespace, source_cluster) (\n  kube_pod_container_info{source_cluster=~\"$cluster\", namespace=~\"$namespace\"}\n  unless on(namespace, pod, container)\n  kube_pod_container_resource_limits{resource=\"memory\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Comparison (Cross-cluster OOM analysis)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 }
  },
  {
   "title": "OOM by Cluster Over Time",
   "type": "timeseries",
   "description": "OOMKilled containers per cluster over time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sum by (source_cluster) (\n  count by (source_cluster, namespace, pod) (\n    max_over_time(\n      {__name__=~\"kube_pod_container_status_(last_terminated|terminated)_reason\", source_cluster=~\"$cluster\", namespace=~\"$namespace\", reason=\"OOMKilled\"}[$__range]\n    ) == 1\n  )\n)",
     "legendFormat": "{{source_cluster}}"
    }
   ]
  },
  {
   "title": "OOM by Cluster & Namespace",
   "type": "table",
   "description": "OOMKilled breakdown by cluster and namespace",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum by (source_cluster, namespace) (\n  count by (source_cluster, namespace, pod) (\n    max_over_time({__name__=~\"kube_pod_container_status_(last_terminated|terminated)_reason\", source_cluster=~\"$cluster\", namespace=~\"$namespace\", reason=\"OOMKilled\"}[$__range])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}