{
 "title": "Konflux Tenant-Level UX Metrics - Per-Tenant",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kueue_admission_wait_time_seconds_sum,source_cluster)"
    }
   },
   {
    "name": "Tenant",
    "query": {
     "query": "label_values(kube_namespace_labels{source_cluster=~\"$Cluster\"},namespace)"
    }
   },
   { "name": "Application" },
   { "name": "Component" }
  ]
 },
 "panels": [
  {
   "title": "Builds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "30-day Average Times for Builds by Component",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    avg by (source_cluster, application, component) (konflux_build_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    avg by (source_cluster, application, component) (konflux_build_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rates for Builds by Component",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_build_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_build_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n  (\n    sum by (source_cluster, application, component) (\n      konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\", event_type=~\"retest-comment|retest-all-comment\"}\n    ) \n    or \n    sum by (source_cluster, application, component) (\n      konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}\n    ) * 0\n  )\n  /\n  sum by (source_cluster, application, component) (\n    konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Volume for Builds by Component",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sort_desc(\n    sum by (source_cluster, application, component) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_build_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_build_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_build_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Build Failure Reasons",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (reason) (konflux_build_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}))",
       "legendFormat": "{{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Integrations (Tests)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "30-day Average Times for Integrations (Tests) by Scenario",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    avg by (source_cluster, application, component, scenario, test_type) (konflux_integration_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    avg by (source_cluster, application, component, scenario, test_type) (konflux_integration_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rates for Integrations (Tests) by Scenario",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n  (\n    sum by (source_cluster, application, component, scenario, test_type) (\n      konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\", event_type=~\"retest-comment|retest-all-comment\"}\n    ) \n    or \n    sum by (source_cluster, application, component, scenario, test_type) (\n      konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}\n    ) * 0\n  )\n  /\n  sum by (source_cluster, application, component, scenario, test_type) (\n    konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Volume for Integrations (Tests) by Scenario",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sort_desc(\n    sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component, scenario, test_type) (konflux_integration_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Integration Failure Reasons",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (reason) (konflux_integration_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}))",
       "legendFormat": "{{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Releases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "30-day Average Times for Releases by Component",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(\n    avg by (source_cluster, application, component) (konflux_release_cr_mean_duration_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    avg by (source_cluster, application, component) (konflux_release_cr_mean_wait_seconds_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rates for Releases by Component",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_release_cr_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_release_cr_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n    /\n    sum by (source_cluster, application, component) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n  (\n    sum by (source_cluster, application, component) (\n      konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\", event_type=~\"retest-comment|retest-all-comment\"}\n    ) \n    or \n    sum by (source_cluster, application, component) (\n      konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}\n    ) * 0\n  )\n  /\n  sum by (source_cluster, application, component) (\n    konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Volume for Releases by Component",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sort_desc(\n    sum by (source_cluster, application, component) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_release_cr_success_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sort_desc(\n    (\n        sum by (source_cluster, application, component) (konflux_release_cr_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})\n        or \n        sum by (source_cluster, application, component) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}) * 0\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Release Failure Reasons",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (reason) (konflux_release_cr_failure_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"}))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Release Automation Adoption %",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\", automated=\"true\"}\n    or\n    konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"} * 0\n)\n/\nsum(konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})"
      }
     ]
    },
    {
     "title": "Automated vs. Manual Releases",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (automated) (konflux_release_cr_total_count_30d{source_cluster=~\"$Cluster\", exported_namespace=~\"${Tenant}\", application=~\"${Application}\", component=~\"${Component}\"})",
       "legendFormat": "{{automated}}"
      }
     ]
    }
   ]
  }
 ]
}