{
 "title": "Konflux UI pods restarts",
 "tags": [ "konflux-ui" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Restart per container image",
   "type": "stat",
   "description": "Pod restarts and restart rate in the last 24h per container image",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (round(increase(kube_pod_container_status_restarts_total{namespace=\"konflux-ui\"}[24h]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restart per cluster",
   "type": "stat",
   "description": "Pod restarts and restart rate in the last 24h per cluster",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(source_cluster) (round(increase(kube_pod_container_status_restarts_total{namespace=\"konflux-ui\"}[24h]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Konflux UI pod restarts per container image",
   "type": "timeseries",
   "description": "Total amount of restarts of Konflux UI pods along the time.",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count by(container) (kube_pod_container_status_restarts_total{namespace=\"konflux-ui\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Konflux UI pod restarts per cluster",
   "type": "timeseries",
   "description": "Total amount of restarts of Konflux UI pods in each cluster along the time.",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "count by(source_cluster) (kube_pod_container_status_restarts_total{namespace=\"konflux-ui\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Pod Restart per container image",
   "type": "stat",
   "description": "Pod restarts and restart rate in the last 24h per container image",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (round(increase(kube_pod_container_status_restarts_total{namespace=\"konflux-ui\"}[24h]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restart per cluster",
   "type": "stat",
   "description": "Pod restarts and restart rate in the last 24h per cluster",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(source_cluster) (round(increase(kube_pod_container_status_restarts_total{namespace=\"konflux-ui\"}[24h]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Konflux UI pod restarts per container image",
   "type": "timeseries",
   "description": "Total amount of restarts of Konflux UI pods along the time.",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "count by(container) (kube_pod_container_status_restarts_total{namespace=\"konflux-ui\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Konflux UI pod restarts per cluster",
   "type": "timeseries",
   "description": "Total amount of restarts of Konflux UI pods in each cluster along the time.",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 29 },
   "targets": [
    {
     "expr": "count by(source_cluster) (kube_pod_container_status_restarts_total{namespace=\"konflux-ui\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}