#!/bin/bash
# Generate per-cluster alerts and tests for absent metrics.
#
# Usage: ./scripts/generate-cluster-monitoring-alert.sh
#
# Inspired by similar script from RHOBS:
# https://gitlab.cee.redhat.com/rhobs/configuration/-/blob/2b32a4d67c132cef113ad4b4e5b5d7b3a591ee0c/scripts/generate-hcp-rules.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${SCRIPT_DIR}/.."

ALERT_FILE="${REPO_ROOT}/rhobs/alerting/data_plane/prometheus.cluster_monitoring_absent_alerts.yaml"
TEST_FILE="${REPO_ROOT}/test/promql/tests/data_plane/cluster_monitoring_absent_test.yaml"

# ============================================================================
# Configuration — edit this section only
# ============================================================================

PROD_CLUSTERS=(
  kflux-fedora-01
  kflux-ocp-p01
  kflux-osp-p01
  kflux-prd-es01
  kflux-prd-rh02
  kflux-prd-rh03
  kflux-rhel-p01
  stone-prd-rh01
  stone-prod-p01
  stone-prod-p02
)

STAGE_CLUSTERS=(
  kflux-stg-es01
  stone-stage-p01
  stone-stg-rh01
)

# Alert template
generate_rule() {
  local cluster="$1"
  cat << EOF

    - alert: ClusterMonitoringAbsent
      expr: absent(up{source_cluster="${cluster}"})
      for: 5m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: "Cluster ${cluster} is not writing up metrics to RHOBS"
        description: >-
          Cluster ${cluster} is not writing up metrics to RHOBS. Possible loss of metrics or cluster is down.
        alert_team_handle: '<!subteam^S06LGCC3C2V> <!subteam^S06V06A36F5> <!subteam^S05Q1P4Q2TG>'
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/o11y/alerting/alert-rules/alert-rule-ClusterMonitoringAbsent.md
        team: o11y
EOF
}

# Test template
generate_test_expectation() {
  local cluster="$1"
  cat << EOF
          - exp_labels:
              severity: critical
              slo: "true"
              source_cluster: ${cluster}
            exp_annotations:
              summary: "Cluster ${cluster} is not writing up metrics to RHOBS"
              description: >-
                Cluster ${cluster} is not writing up metrics to RHOBS. Possible loss of metrics or cluster is down.
              alert_team_handle: '<!subteam^S06LGCC3C2V> <!subteam^S06V06A36F5> <!subteam^S05Q1P4Q2TG>'
              runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/o11y/alerting/alert-rules/alert-rule-ClusterMonitoringAbsent.md
              team: o11y
EOF
}

# ============================================================================
# Generation logic — SHOULD NOT BE EDITED IF NOT NECESSARY
# ============================================================================

ALL_CLUSTERS=("${PROD_CLUSTERS[@]}" "${STAGE_CLUSTERS[@]}")

# --- Generate alert file ---
cat > "$ALERT_FILE" << 'HEADER'
# This file is auto-generated by scripts/generate-cluster-monitoring-alert.sh
# DO NOT EDIT DIRECTLY — update the configuration in the script and re-run.
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-cluster-monitoring-absent-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: cluster_monitoring_absent
    interval: 1m
    rules:
HEADER

for cluster in "${ALL_CLUSTERS[@]}"; do
  generate_rule "$cluster" >> "$ALERT_FILE"
done

echo "Generated ${ALERT_FILE}"

# --- Generate test file ---
cat > "$TEST_FILE" << 'HEADER'
# This file is auto-generated by scripts/generate-cluster-monitoring-alert.sh
# DO NOT EDIT DIRECTLY — update the configuration in the script and re-run.
evaluation_interval: 1m

rule_files:
  - prometheus.cluster_monitoring_absent_alerts.yaml

tests:
  # Test 1: When metrics are absent for a cluster, alert should fire
  - interval: 1m
    input_series: []
    alert_rule_test:
      - alertname: ClusterMonitoringAbsent
        eval_time: 10m
        exp_alerts:
HEADER

for cluster in "${ALL_CLUSTERS[@]}"; do
  generate_test_expectation "$cluster" >> "$TEST_FILE"
done

cat >> "$TEST_FILE" << 'FOOTER'

  # Test 2: When metrics are present for a cluster, alert should NOT fire
  - interval: 1m
    input_series:
FOOTER

for cluster in "${ALL_CLUSTERS[@]}"; do
  cat >> "$TEST_FILE" << EOF
      - series: 'up{source_cluster="${cluster}"}'
        values: '1x15'
EOF
done

cat >> "$TEST_FILE" << 'FOOTER'
    alert_rule_test:
      - alertname: ClusterMonitoringAbsent
        eval_time: 10m
        exp_alerts: []
FOOTER

echo "Generated ${TEST_FILE}"

# --- Run validation ---
echo "Running check-and-test..."
make -C "$REPO_ROOT" selective-check-and-test \
  RULE_FILES="rhobs/alerting/data_plane/$(basename "$ALERT_FILE")" \
  TEST_CASE_FILES="test/promql/tests/data_plane/$(basename "$TEST_FILE")"
