name: Validate PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=5m
          only-new-issues: true

  security_scan:
    name: Security scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.28.0
        with:
          args: '-exclude-generated -no-fail -fmt sarif -out results.sarif ./...'
        env:
          GOROOT: ""
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
