name: Lint manifests with yamllint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv sync --dev
      - name: Lint yaml manifests
        run: |
          pipenv run yamllint -f github --no-warnings .
      - name: Check for yaml lint warnings
        if: success() || failure()
        continue-on-error: true
        run: |
          pipenv run yamllint -f github -s .
